package com.smartbox.investory.accounting;

public enum AccountingFilingIssueCode {
  NOT_CONFIRMED,
  CALCULATION_INCOMPLETE,
  SOURCE_REVIEW_REQUIRED,
  MISSING_TAXPAYER_CONFIGURATION,
  MISSING_PAYMENT_CONFIGURATION,
  MISSING_COUNTERPARTY_IDENTIFIER,
  MISSING_JPK_EVIDENCE_CLASSIFICATION,
  UNSUPPORTED_VAT_RATE,
  JPK_VALIDATION_FAILED
}
