package com.smartbox.investory.accounting;

public enum VatTreatment {
  DOMESTIC_VAT,
  EU_B2B_REVERSE_CHARGE,
  NON_EU_B2B_OUTSIDE_POLAND,
  VAT_EXEMPT,
  DOMESTIC_PURCHASE,
  IMPORT_OF_SERVICES_EU,
  IMPORT_OF_SERVICES_NON_EU
}
