CREATE TABLE IF NOT EXISTS investory.fx_daily_rates (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rate_date date NOT NULL,
    base varchar(3) NOT NULL REFERENCES investory.currencies(id),
    to_currency varchar(3) NOT NULL REFERENCES investory.currencies(id),
    rate numeric(20,8) NOT NULL CHECK (rate > 0),
    source varchar(32) NOT NULL,
    method varchar(32) NOT NULL CHECK (method IN ('OBSERVED', 'INTERPOLATED', 'CARRY_FORWARD')),
    source_rate_date date NOT NULL,
    source_reference varchar(256),
    CONSTRAINT chk_fx_daily_distinct_currencies CHECK (base <> to_currency),
    CONSTRAINT ux_fx_daily_rate UNIQUE (rate_date, base, to_currency)
);

CREATE INDEX IF NOT EXISTS ix_fx_daily_lookup
    ON investory.fx_daily_rates (rate_date, base, to_currency);

ALTER FUNCTION investory.resolve_fx_rate(date, varchar, varchar)
    RENAME TO resolve_fx_rate_legacy;

CREATE OR REPLACE FUNCTION investory.resolve_fx_rate(
    p_valuation_date date,
    p_source_currency varchar(3),
    p_target_currency varchar(3)
) RETURNS TABLE (
    source_currency varchar(3), target_currency varchar(3), fx_rate_to_target numeric,
    source varchar(64), rate_method varchar(32), rate_source varchar(32),
    source_rate_date date, age_days integer, conversion_status varchar(32)
) LANGUAGE sql STABLE AS $$
SELECT p_source_currency,
       p_target_currency,
       COALESCE(d.rate, legacy.fx_rate_to_target),
       COALESCE(d.source, legacy.source),
       CASE WHEN d.rate IS NOT NULL THEN d.method
            WHEN legacy.rate_method = 'HISTORICAL_MONTHLY' THEN 'CARRY_FORWARD'
            WHEN legacy.source_rate_date < p_valuation_date THEN 'CARRY_FORWARD'
            ELSE legacy.rate_method END,
       COALESCE(d.source, legacy.rate_source),
       COALESCE(d.source_rate_date, legacy.source_rate_date),
       COALESCE((p_valuation_date - d.source_rate_date)::integer, legacy.age_days),
       COALESCE(
           CASE WHEN d.method = 'OBSERVED' THEN 'OK'
                WHEN d.method = 'INTERPOLATED' THEN 'ESTIMATED'
                WHEN d.method = 'CARRY_FORWARD' THEN 'CARRY_FORWARD'
                ELSE NULL END,
           CASE WHEN legacy.rate_method = 'HISTORICAL_MONTHLY' THEN 'CARRY_FORWARD'
                WHEN legacy.source_rate_date < p_valuation_date THEN 'CARRY_FORWARD'
                ELSE legacy.conversion_status END,
           CASE WHEN p_source_currency = p_target_currency THEN 'SAME_CURRENCY'
                ELSE 'MISSING_RATE' END)
FROM (SELECT 1) sentinel
LEFT JOIN LATERAL (
    SELECT rate, source, method, source_rate_date
    FROM investory.fx_daily_rates
    WHERE rate_date = p_valuation_date
      AND base = p_source_currency
      AND to_currency = p_target_currency
) d ON true
LEFT JOIN LATERAL (
    SELECT * FROM investory.resolve_fx_rate_legacy(
        p_valuation_date, p_source_currency, p_target_currency)
) legacy ON d.rate IS NULL;
$$;

COMMENT ON TABLE investory.fx_daily_rates IS
    'Canonical daily neutral FX rates. One row per calendar date and directed currency pair.';
