SET search_path TO investory, public;

CREATE TABLE IF NOT EXISTS investory.simulation_plans (
    id bigserial PRIMARY KEY,
    portfolio_id bigint NOT NULL REFERENCES investory.portfolios(id) ON DELETE CASCADE,
    name varchar(255) NOT NULL,
    current_revision_id bigint,
    archived boolean NOT NULL DEFAULT false,
    sandbox boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (btrim(name) <> ''),
    UNIQUE (portfolio_id, name)
);

CREATE INDEX IF NOT EXISTS ix_simulation_plans_portfolio ON investory.simulation_plans(portfolio_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_simulation_plans_one_sandbox_per_portfolio
    ON investory.simulation_plans (portfolio_id)
    WHERE sandbox AND NOT archived;

CREATE TABLE IF NOT EXISTS investory.simulation_plan_revisions (
    id bigserial PRIMARY KEY,
    simulation_plan_id bigint NOT NULL REFERENCES investory.simulation_plans(id) ON DELETE RESTRICT,
    revision_number integer NOT NULL CHECK (revision_number > 0),
    current_age integer NOT NULL,
    start_year integer NOT NULL,
    end_age integer NOT NULL,
    retirement_age integer,
    annual_employment_income numeric(30,12),
    annual_pre_retirement_contribution numeric(30,12),
    annual_living_expenses numeric(30,12) NOT NULL,
    annual_discretionary_expenses numeric(30,12) NOT NULL,
    inflation_rate numeric(20,12) NOT NULL,
    rental_income_growth_rate numeric(20,12) NOT NULL,
    spending_growth_rate numeric(20,12) NOT NULL,
    funding_strategy varchar(32),
    funding_order varchar(64) NOT NULL DEFAULT 'RESERVE,LONG_TERM,INVESTMENT',
    expense_profile varchar(512),
    safe_reserve_years numeric(20,12) DEFAULT 5,
    equity_harvest_minimum_return_rate numeric(20,12) DEFAULT 0.07,
    equity_gain_harvest_rate numeric(20,12) DEFAULT 0.75,
    allow_emergency_equity_withdrawal boolean DEFAULT false,
    fixed_income_return_rate numeric(20,12) NOT NULL,
    equity_return_rate numeric(20,12) NOT NULL,
    pension_start_age integer NOT NULL,
    annual_pension numeric(30,12) NOT NULL,
    capital_gain_tax_rate numeric(20,12) NOT NULL,
    baseline_as_of_year integer,
    baseline_reserve numeric(30,12),
    baseline_investment_capital numeric(30,12),
    baseline_long_term_capital numeric(30,12),
    baseline_rental_income numeric(30,12),
    baseline_long_term_income numeric(30,12),
    baseline_long_term_state text,
    baseline_long_term_state_version integer,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_simulation_plan_revisions_plan_number
        UNIQUE (simulation_plan_id, revision_number),
    CONSTRAINT uq_simulation_plan_revisions_id_plan
        UNIQUE (id, simulation_plan_id)
);

COMMENT ON TABLE investory.simulation_plan_revisions IS
    'Immutable Base assumption snapshots. Editing a logical plan creates a new revision.';
COMMENT ON COLUMN investory.simulation_plan_revisions.baseline_as_of_year IS
    'As-of year for the frozen economic planning baseline; null means legacy revision.';

ALTER TABLE investory.simulation_plans
    ADD CONSTRAINT fk_simulation_plans_current_revision
        FOREIGN KEY (current_revision_id, id)
        REFERENCES investory.simulation_plan_revisions (id, simulation_plan_id);

CREATE TABLE IF NOT EXISTS investory.simulation_plan_revision_events (
    id bigserial PRIMARY KEY,
    logical_event_id bigint,
    revision_id bigint NOT NULL REFERENCES investory.simulation_plan_revisions(id) ON DELETE RESTRICT,
    event_year integer NOT NULL,
    name varchar(255) NOT NULL,
    amount numeric(30,12) NOT NULL,
    event_type varchar(32) NOT NULL,
    notes varchar(1023),
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_simulation_plan_revision_events_revision_year
    ON investory.simulation_plan_revision_events(revision_id, event_year, id);
CREATE INDEX IF NOT EXISTS ix_simulation_plan_revision_events_logical_id
    ON investory.simulation_plan_revision_events(logical_event_id);

COMMENT ON TABLE investory.simulation_plan_revision_events IS
    'Immutable life-event snapshots owned by a simulation plan revision.';
COMMENT ON COLUMN investory.simulation_plan_revision_events.logical_event_id IS
    'Stable logical event identity copied across immutable plan revisions; null only for legacy rows.';

CREATE TABLE IF NOT EXISTS investory.planning_years (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id bigint NOT NULL REFERENCES investory.portfolios(id) ON DELETE CASCADE,
    planning_year integer NOT NULL,
    status varchar(16) NOT NULL,
    baseline_plan_id bigint,
    baseline_revision_id bigint,
    baseline_created_at timestamptz,
    closed_at timestamptz,
    reopened_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_planning_years_portfolio_year UNIQUE (portfolio_id, planning_year),
    CONSTRAINT ck_planning_years_baseline_revision_pair
        CHECK ((baseline_plan_id IS NULL) = (baseline_revision_id IS NULL)),
    CONSTRAINT fk_planning_years_baseline_revision
        FOREIGN KEY (baseline_revision_id, baseline_plan_id)
        REFERENCES investory.simulation_plan_revisions (id, simulation_plan_id)
);

CREATE TABLE IF NOT EXISTS investory.planning_year_values (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    planning_year_id bigint NOT NULL REFERENCES investory.planning_years(id) ON DELETE CASCADE,
    value_kind varchar(16) NOT NULL,
    metric varchar(48) NOT NULL,
    derived_value numeric(30,12),
    approved_value numeric(30,12),
    source_type varchar(32) NOT NULL,
    note varchar(1000),
    captured_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_planning_year_values_key UNIQUE (planning_year_id, value_kind, metric)
);

COMMENT ON TABLE investory.planning_years IS
    'Planning-only annual lifecycle and expectation baseline. It is downstream from accounting.';
COMMENT ON COLUMN investory.planning_years.baseline_revision_id IS
    'Exact immutable plan revision used to create this baseline; null only for legacy/unmapped data.';
COMMENT ON TABLE investory.planning_year_values IS
    'Planning-only derived, approved, and baseline values. Never an accounting fact table.';

CREATE SEQUENCE investory.long_term_asset_id_seq;

CREATE TABLE investory.bond (
    id bigint PRIMARY KEY DEFAULT nextval('investory.long_term_asset_id_seq'),
    portfolio_id bigint NOT NULL REFERENCES investory.portfolios(id) ON DELETE CASCADE,
    name varchar(255) NOT NULL,
    currency varchar(3) NOT NULL REFERENCES investory.currencies(id),
    value numeric(30,12) NOT NULL CHECK (value >= 0),
    acquisition_date date,
    interest_rate numeric(20,12) NOT NULL CHECK (interest_rate >= 0),
    maturity_date date NOT NULL,
    archived_at date,
    notes text,
    external_key varchar(128),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (btrim(name) <> '')
);
CREATE INDEX ix_bond_portfolio_active ON investory.bond(portfolio_id, archived_at);
CREATE UNIQUE INDEX ux_bond_portfolio_external_key ON investory.bond(portfolio_id, external_key)
    WHERE external_key IS NOT NULL;

CREATE TABLE investory.real_estate (
    id bigint PRIMARY KEY DEFAULT nextval('investory.long_term_asset_id_seq'),
    portfolio_id bigint NOT NULL REFERENCES investory.portfolios(id) ON DELETE CASCADE,
    name varchar(255) NOT NULL,
    currency varchar(3) NOT NULL REFERENCES investory.currencies(id),
    value numeric(30,12) NOT NULL CHECK (value >= 0),
    tax_base numeric(30,12) CHECK (tax_base IS NULL OR tax_base >= 0),
    acquisition_date date,
    land_register_number varchar(128),
    archived_at date,
    notes text,
    external_key varchar(128),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (btrim(name) <> '')
);
CREATE INDEX ix_real_estate_portfolio_active ON investory.real_estate(portfolio_id, archived_at);
COMMENT ON COLUMN investory.real_estate.tax_base IS
    'Annual rental-tax base. Annual rental tax = tax_base * 0.085.';
CREATE UNIQUE INDEX ux_real_estate_portfolio_land_register
    ON investory.real_estate(portfolio_id, land_register_number)
    WHERE land_register_number IS NOT NULL AND btrim(land_register_number) <> '';
CREATE UNIQUE INDEX ux_real_estate_portfolio_external_key ON investory.real_estate(portfolio_id, external_key)
    WHERE external_key IS NOT NULL;

CREATE TABLE investory.cash_reserve (
    id bigint PRIMARY KEY DEFAULT nextval('investory.long_term_asset_id_seq'),
    portfolio_id bigint NOT NULL REFERENCES investory.portfolios(id) ON DELETE CASCADE,
    name varchar(255) NOT NULL,
    currency varchar(3) NOT NULL REFERENCES investory.currencies(id),
    value numeric(30,12) NOT NULL CHECK (value >= 0),
    acquisition_date date,
    interest_rate numeric(20,12) NOT NULL DEFAULT 0 CHECK (interest_rate >= 0),
    maturity_date date,
    archived_at date,
    notes text,
    external_key varchar(128),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (btrim(name) <> '')
);
CREATE INDEX ix_cash_reserve_portfolio_active ON investory.cash_reserve(portfolio_id, archived_at);
CREATE UNIQUE INDEX ux_cash_reserve_portfolio_external_key ON investory.cash_reserve(portfolio_id, external_key)
    WHERE external_key IS NOT NULL;

CREATE TABLE investory.personal_asset (
    id bigint PRIMARY KEY DEFAULT nextval('investory.long_term_asset_id_seq'),
    portfolio_id bigint NOT NULL REFERENCES investory.portfolios(id) ON DELETE CASCADE,
    name varchar(255) NOT NULL,
    category varchar(16) NOT NULL CHECK (category IN ('HOME', 'VEHICLE', 'OTHER')),
    currency varchar(3) NOT NULL REFERENCES investory.currencies(id),
    value numeric(30,12) NOT NULL CHECK (value >= 0),
    acquisition_date date,
    archived_at date,
    notes text,
    external_key varchar(128),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (btrim(name) <> '')
);
CREATE INDEX ix_personal_asset_portfolio_active ON investory.personal_asset(portfolio_id, archived_at);
CREATE UNIQUE INDEX ux_personal_asset_portfolio_external_key ON investory.personal_asset(portfolio_id, external_key)
    WHERE external_key IS NOT NULL;

CREATE TABLE investory.rental_contract (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    real_estate_id bigint NOT NULL REFERENCES investory.real_estate(id) ON DELETE CASCADE,
    start_date date NOT NULL,
    end_date date,
    terminated_date date,
    bootstrap_managed boolean NOT NULL DEFAULT false,
    tenant_name varchar(200),
    tenant_email varchar(320),
    tenant_phone varchar(50),
    notes text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (end_date IS NULL OR end_date >= start_date),
    CHECK (terminated_date IS NULL OR terminated_date >= start_date)
);
CREATE INDEX ix_rental_contract_real_estate_dates ON investory.rental_contract(real_estate_id, start_date DESC);

CREATE TABLE investory.rental_contract_term (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rental_contract_id bigint NOT NULL REFERENCES investory.rental_contract(id) ON DELETE CASCADE,
    cash_flow_type varchar(32) NOT NULL CHECK (cash_flow_type IN
        ('RENT', 'PARKING_RENT', 'ADMIN_FEE', 'UTILITIES', 'PROPERTY_TAX', 'INSURANCE', 'OTHER_INCOME', 'OTHER_EXPENSE')),
    amount numeric(30,12) NOT NULL CHECK (amount >= 0),
    frequency varchar(16) NOT NULL CHECK (frequency IN ('MONTHLY', 'ANNUAL')),
    paid_by_tenant boolean NOT NULL DEFAULT false,
    UNIQUE (rental_contract_id, cash_flow_type)
);
CREATE INDEX ix_rental_contract_term_contract ON investory.rental_contract_term(rental_contract_id, cash_flow_type);

CREATE TABLE investory.real_estate_valuation (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    real_estate_id bigint NOT NULL REFERENCES investory.real_estate(id) ON DELETE CASCADE,
    valuation_date date NOT NULL,
    value numeric(30,12) NOT NULL CHECK (value >= 0),
    UNIQUE (real_estate_id, valuation_date)
);
CREATE INDEX ix_real_estate_valuation_dates ON investory.real_estate_valuation(real_estate_id, valuation_date DESC);

SELECT setval('investory.rental_contract_id_seq', COALESCE((SELECT max(id) FROM investory.rental_contract), 1),
             EXISTS (SELECT 1 FROM investory.rental_contract));
SELECT setval('investory.rental_contract_term_id_seq', COALESCE((SELECT max(id) FROM investory.rental_contract_term), 1),
             EXISTS (SELECT 1 FROM investory.rental_contract_term));
SELECT setval('investory.real_estate_valuation_id_seq', COALESCE((SELECT max(id) FROM investory.real_estate_valuation), 1),
             EXISTS (SELECT 1 FROM investory.real_estate_valuation));

CREATE VIEW investory.app_v_long_term_assets AS
SELECT id, portfolio_id, 'BOND' AS asset_type, name, currency, value AS current_value, acquisition_date, archived_at FROM investory.bond
UNION ALL SELECT id, portfolio_id, 'REAL_ESTATE', name, currency, value, acquisition_date, archived_at FROM investory.real_estate
UNION ALL SELECT id, portfolio_id, 'CASH_RESERVE', name, currency, value, acquisition_date, archived_at FROM investory.cash_reserve
UNION ALL SELECT id, portfolio_id, 'PERSONAL_ASSET', name, currency, value, acquisition_date, archived_at FROM investory.personal_asset;

CREATE VIEW investory.recon_v_long_term_assets AS
WITH asset_ids AS (
    SELECT id, portfolio_id FROM investory.real_estate
    UNION ALL SELECT id, portfolio_id FROM investory.bond
    UNION ALL SELECT id, portfolio_id FROM investory.cash_reserve
    UNION ALL SELECT id, portfolio_id FROM investory.personal_asset
), duplicate_ids AS (
    SELECT id, min(portfolio_id) AS portfolio_id, count(*) AS occurrences
    FROM asset_ids GROUP BY id HAVING count(*) > 1
), orphan_contracts AS (
    SELECT c.id, c.real_estate_id AS asset_id FROM investory.rental_contract c
    WHERE NOT EXISTS (SELECT 1 FROM investory.real_estate r WHERE r.id = c.real_estate_id)
)
SELECT 'LT_ASSET_ID_COLLISION' AS issue_code, id AS asset_id, portfolio_id,
       'same id occurs in multiple explicit asset tables' AS details FROM duplicate_ids
UNION ALL
SELECT 'LT_RENTAL_CONTRACT_ORPHAN', asset_id, NULL::bigint,
       'rental contract has no real-estate parent' FROM orphan_contracts;

COMMENT ON VIEW investory.recon_v_long_term_assets IS
    'Narrow structural diagnostics for explicit Long-Term asset persistence; contains no financial calculations.';


-- Squashed post-V01.008 migrations.
-- Source: V01.009__long_term_tax_and_chronology.sql
-- Preserve the annual tax-base contract and make the formula explicit without rewriting facts.
COMMENT ON COLUMN investory.real_estate.tax_base IS
    'Annual rental-tax base in asset currency. Annual rental tax = tax_base * 0.085; NULL means unspecified.';

ALTER TABLE investory.bond
    ADD CONSTRAINT ck_bond_maturity_after_acquisition
        CHECK (acquisition_date IS NULL OR maturity_date >= acquisition_date);

ALTER TABLE investory.cash_reserve
    ADD CONSTRAINT ck_cash_reserve_maturity_after_acquisition
        CHECK (acquisition_date IS NULL OR maturity_date IS NULL OR maturity_date >= acquisition_date);

ALTER TABLE investory.rental_contract
    ADD CONSTRAINT ck_rental_contract_termination_before_expected_end
        CHECK (terminated_date IS NULL OR end_date IS NULL OR terminated_date <= end_date);

-- Historical availability must be proven. Existing assets are deliberately not backfilled because
-- archived_at alone cannot show whether an asset was previously archived and reactivated.
CREATE TABLE investory.long_term_asset_history (
    asset_id bigint PRIMARY KEY,
    asset_type varchar(32) NOT NULL,
    complete boolean NOT NULL DEFAULT false,
    CONSTRAINT ck_long_term_asset_history_type
        CHECK (asset_type IN ('REAL_ESTATE', 'BOND', 'CASH_RESERVE', 'PERSONAL_ASSET'))
);

CREATE TABLE investory.long_term_asset_archive_interval (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id bigint NOT NULL
        REFERENCES investory.long_term_asset_history(asset_id),
    archived_from date NOT NULL,
    archived_to date,
    CONSTRAINT ck_long_term_asset_archive_interval_dates
        CHECK (archived_to IS NULL OR archived_to >= archived_from)
);

CREATE UNIQUE INDEX uq_long_term_asset_archive_interval_open
    ON investory.long_term_asset_archive_interval(asset_id)
    WHERE archived_to IS NULL;

-- Source: V01.010__remove_unused_real_estate_valuation.sql
-- Dated property observations have no runtime writer or reader. Keep current value on real_estate.
DROP TABLE investory.real_estate_valuation;

-- Source: V01.011__retirement_canonical_persistence.sql
SET search_path TO investory, public;

-- Canonical retirement storage. A plan is mutable user intent; projections are runtime-only.
CREATE TABLE IF NOT EXISTS investory.retirement_plans (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id bigint NOT NULL REFERENCES investory.portfolios(id) ON DELETE CASCADE,
    name varchar(255) NOT NULL,
    birth_date date,
    effective_year integer NOT NULL,
    end_age integer NOT NULL,
    retirement_age integer,
    annual_employment_income numeric(30,12),
    annual_pre_retirement_contribution numeric(30,12),
    annual_living_expenses numeric(30,12) NOT NULL,
    annual_discretionary_expenses numeric(30,12) NOT NULL,
    inflation_rate numeric(20,12) NOT NULL,
    rental_income_growth_rate numeric(20,12) NOT NULL,
    spending_growth_rate numeric(20,12) NOT NULL,
    funding_strategy varchar(32),
    funding_order varchar(64) NOT NULL DEFAULT 'RESERVE,LONG_TERM,INVESTMENT',
    expense_profile varchar(512),
    safe_reserve_years numeric(20,12) DEFAULT 5,
    equity_harvest_minimum_return_rate numeric(20,12) DEFAULT 0.07,
    equity_gain_harvest_rate numeric(20,12) DEFAULT 0.75,
    allow_emergency_equity_withdrawal boolean DEFAULT false,
    fixed_income_return_rate numeric(20,12) NOT NULL,
    equity_return_rate numeric(20,12) NOT NULL,
    pension_start_age integer NOT NULL,
    annual_pension numeric(30,12) NOT NULL,
    capital_gain_tax_rate numeric(20,12) NOT NULL,
    baseline_as_of_year integer,
    baseline_reserve numeric(30,12),
    baseline_investment_capital numeric(30,12),
    baseline_long_term_capital numeric(30,12),
    baseline_rental_income numeric(30,12),
    baseline_long_term_income numeric(30,12),
    baseline_long_term_state text,
    baseline_long_term_state_version integer,
    archived boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (btrim(name) <> ''),
    UNIQUE (portfolio_id, name)
);

CREATE INDEX IF NOT EXISTS ix_retirement_plans_portfolio
    ON investory.retirement_plans(portfolio_id);

CREATE TABLE IF NOT EXISTS investory.retirement_plan_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id bigint NOT NULL REFERENCES investory.retirement_plans(id) ON DELETE CASCADE,
    event_year integer NOT NULL,
    name varchar(255) NOT NULL,
    amount numeric(30,12) NOT NULL,
    event_type varchar(32) NOT NULL,
    notes varchar(1023),
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_retirement_plan_events_plan_year
    ON investory.retirement_plan_events(plan_id, event_year, id);

CREATE TABLE IF NOT EXISTS investory.retirement_planning_years (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id bigint NOT NULL REFERENCES investory.portfolios(id) ON DELETE CASCADE,
    planning_year integer NOT NULL,
    status varchar(16) NOT NULL,
    state jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (portfolio_id, planning_year)
);

COMMENT ON TABLE investory.retirement_plans IS
    'Mutable persisted retirement intent. Current age and future projections are derived at runtime.';
COMMENT ON TABLE investory.retirement_plan_events IS
    'Mutable plan events. Events are not copied into immutable revision snapshots.';
COMMENT ON TABLE investory.retirement_planning_years IS
    'Persisted historical/reviewed planning state only; generated future projections are not stored.';

-- Forward migration from the legacy model. Keep IDs so canonical fixtures and ownership links remain stable.
INSERT INTO investory.retirement_plans (
    id, portfolio_id, name, birth_date, effective_year, end_age, retirement_age,
    annual_employment_income, annual_pre_retirement_contribution, annual_living_expenses,
    annual_discretionary_expenses, inflation_rate, rental_income_growth_rate,
    spending_growth_rate, funding_strategy, funding_order, expense_profile, safe_reserve_years,
    equity_harvest_minimum_return_rate, equity_gain_harvest_rate, allow_emergency_equity_withdrawal,
    fixed_income_return_rate, equity_return_rate, pension_start_age, annual_pension,
    capital_gain_tax_rate, baseline_as_of_year, baseline_reserve, baseline_investment_capital,
    baseline_long_term_capital, baseline_rental_income, baseline_long_term_income,
    baseline_long_term_state, baseline_long_term_state_version, archived, created_at, updated_at)
SELECT p.id, p.portfolio_id, p.name,
       make_date(r.start_year - r.current_age, 1, 1), r.start_year, r.end_age, r.retirement_age,
       r.annual_employment_income, r.annual_pre_retirement_contribution, r.annual_living_expenses,
       r.annual_discretionary_expenses, r.inflation_rate, r.rental_income_growth_rate,
       r.spending_growth_rate, r.funding_strategy, r.funding_order, r.expense_profile, r.safe_reserve_years,
       r.equity_harvest_minimum_return_rate, r.equity_gain_harvest_rate, r.allow_emergency_equity_withdrawal,
       r.fixed_income_return_rate, r.equity_return_rate, r.pension_start_age, r.annual_pension,
       r.capital_gain_tax_rate, r.baseline_as_of_year, r.baseline_reserve, r.baseline_investment_capital,
       r.baseline_long_term_capital, r.baseline_rental_income, r.baseline_long_term_income,
       r.baseline_long_term_state, r.baseline_long_term_state_version, p.archived,
       p.created_at, p.updated_at
FROM investory.simulation_plans p
JOIN investory.simulation_plan_revisions r
  ON r.id = p.current_revision_id AND r.simulation_plan_id = p.id
WHERE NOT p.sandbox
ON CONFLICT (id) DO NOTHING;

INSERT INTO investory.retirement_plan_events
    (id, plan_id, event_year, name, amount, event_type, notes, created_at)
SELECT e.id, r.simulation_plan_id, e.event_year, e.name, e.amount, e.event_type, e.notes, e.created_at
FROM investory.simulation_plan_revision_events e
JOIN investory.simulation_plan_revisions r ON r.id = e.revision_id
JOIN investory.retirement_plans p ON p.id = r.simulation_plan_id
WHERE r.id = (SELECT current_revision_id FROM investory.simulation_plans WHERE id = r.simulation_plan_id)
ON CONFLICT (id) DO NOTHING;

INSERT INTO investory.retirement_planning_years
    (id, portfolio_id, planning_year, status, state, created_at, updated_at)
SELECT py.id,
       py.portfolio_id,
       py.planning_year,
       py.status,
       jsonb_strip_nulls(jsonb_build_object(
           'baselinePlanId', py.baseline_plan_id,
           'baselineCreatedAt', py.baseline_created_at,
           'closedAt', py.closed_at,
           'reopenedAt', py.reopened_at,
           'values', jsonb_build_object(
               'ACTUAL', COALESCE((
                   SELECT jsonb_object_agg(v.metric, jsonb_strip_nulls(jsonb_build_object(
                       'metric', v.metric,
                       'derivedValue', v.derived_value,
                       'approvedValue', v.approved_value,
                       'source', v.source_type,
                       'note', v.note)))
                   FROM investory.planning_year_values v
                   WHERE v.planning_year_id = py.id AND v.value_kind = 'ACTUAL'), '{}'::jsonb),
               'BASELINE', COALESCE((
                   SELECT jsonb_object_agg(v.metric, jsonb_strip_nulls(jsonb_build_object(
                       'metric', v.metric,
                       'derivedValue', v.derived_value,
                       'approvedValue', v.approved_value,
                       'source', v.source_type,
                       'note', v.note)))
                   FROM investory.planning_year_values v
                   WHERE v.planning_year_id = py.id AND v.value_kind = 'BASELINE'), '{}'::jsonb)))),
       py.created_at,
       py.updated_at
FROM investory.planning_years py
ON CONFLICT (id) DO NOTHING;

SELECT setval(
    pg_get_serial_sequence('investory.retirement_plans', 'id'),
    COALESCE((SELECT MAX(id) FROM investory.retirement_plans), 1),
    true);
SELECT setval(
    pg_get_serial_sequence('investory.retirement_plan_events', 'id'),
    COALESCE((SELECT MAX(id) FROM investory.retirement_plan_events), 1),
    true);
SELECT setval(
    pg_get_serial_sequence('investory.retirement_planning_years', 'id'),
    COALESCE((SELECT MAX(id) FROM investory.retirement_planning_years), 1),
    true);

-- The canonical stores are now populated. Remove the revision and EAV persistence models so
-- application code cannot accidentally keep both paths alive.
DROP TABLE investory.planning_year_values;
DROP TABLE investory.planning_years;
DROP TABLE investory.simulation_plan_revision_events;
ALTER TABLE investory.simulation_plans DROP CONSTRAINT fk_simulation_plans_current_revision;
DROP TABLE investory.simulation_plan_revisions;
DROP TABLE investory.simulation_plans;

-- Source: V01.012__long_term_rental_overlap_guard.sql
-- Effective rental periods are closed on both dates. The upper bound is made exclusive
-- so contracts ending on one day may be followed by a contract starting the next day.
CREATE EXTENSION IF NOT EXISTS btree_gist;

ALTER TABLE investory.rental_contract
    ADD CONSTRAINT ex_rental_contract_non_overlapping_effective_periods
    EXCLUDE USING gist (
        real_estate_id WITH =,
        daterange(
            start_date,
            least(
                coalesce(end_date, 'infinity'::date),
                coalesce(terminated_date, 'infinity'::date)
            ) + 1,
            '[)'
        ) WITH &&
    );

-- Source: V01.013__dashboard_open_position_regression.sql
SET search_path TO investory, public;

-- V01.005 was already deployed before its final current-position definition was
-- consolidated. Re-apply the definition so upgraded databases keep holdings
-- visible when current price or FX is unavailable.
CREATE OR REPLACE VIEW investory.app_v_current_open_position_rows AS
SELECT
    pf.id AS portfolio_id,
    pf.base_currency::varchar(3) AS base_currency,
    a.id AS account_id,
    a.currency::varchar(3) AS account_currency,
    asset.id AS asset_id,
    asset.symbol AS asset_symbol,
    p.id AS position_id,
    p.cost_currency::varchar(3) AS cost_basis_currency,
    investory.signed_position_quantity(p.operation, p.volume) AS volume,
    COALESCE(p.purchase_value, p.volume * p.open_price, 0) AS cost_basis_native,
    price.selected_price AS market_price,
    price.price_currency::varchar(3) AS market_price_currency,
    price.price_selection_source,
    price.selected_price_date,
    price.price_source,
    price.source_symbol AS market_price_source_symbol,
    cost_fx.fx_rate_to_base AS cost_basis_to_base_rate,
    cost_fx.conversion_status AS cost_basis_fx_status,
    market_fx.fx_rate_to_base AS market_price_to_base_rate,
    market_fx.conversion_status AS market_price_fx_status,
    CASE
        WHEN investory.fx_status_usable(cost_fx.conversion_status)
            THEN COALESCE(p.purchase_value, p.volume * p.open_price, 0) * cost_fx.fx_rate_to_base
        ELSE NULL::numeric
    END AS cost_basis_in_base_currency,
    CASE
        WHEN price.selected_price IS NOT NULL
         AND investory.fx_status_usable(market_fx.conversion_status)
            THEN investory.signed_position_quantity(p.operation, p.volume)
                 * price.selected_price
                 * CASE WHEN price.quality_class LIKE '%PERCENT_OF_PAR%' THEN 0.01::numeric
                        ELSE 1::numeric END
                 * market_fx.fx_rate_to_base
        ELSE NULL::numeric
    END AS market_value_in_base_currency
FROM investory.positions p
JOIN investory.accounts a ON a.id = p.account_id
JOIN investory.portfolios pf ON pf.id = a.portfolio_id
JOIN investory.assets asset ON asset.id = p.asset_id
LEFT JOIN investory.app_v_current_asset_price_mv price ON price.asset_id = asset.id
LEFT JOIN investory.app_v_portfolio_daily_fx_rate_mv cost_fx
  ON cost_fx.portfolio_id = pf.id
 AND cost_fx.valuation_date = CURRENT_DATE
 AND cost_fx.source_currency = p.cost_currency::varchar(3)
LEFT JOIN investory.app_v_portfolio_daily_fx_rate_mv market_fx
  ON market_fx.portfolio_id = pf.id
 AND market_fx.valuation_date = CURRENT_DATE
 AND market_fx.source_currency = price.price_currency::varchar(3)
WHERE p.close_time IS NULL
  AND asset.exclude_from_import = false
  AND COALESCE(p.volume, 0) > 0;

COMMENT ON VIEW investory.app_v_current_open_position_rows IS
    'Shared current open-position valuation rows. Uses current valuation FX; stale or missing FX yields null converted values.';

-- Source: V01.014__dashboard_known_value_aggregation.sql
-- Rebuild dependents around account statistics because PostgreSQL cannot replace a
-- materialized view while another view depends on it.
-- Known valued rows remain additive; missing valuation is reported by missing_fx_count.
DROP TABLE IF EXISTS _account_stats_dependent_defs;
DROP TABLE IF EXISTS _account_stats_dependent_mv_defs;
DROP TABLE IF EXISTS _account_stats_dependent_indexes;
CREATE TEMP TABLE _account_stats_dependent_defs AS
SELECT c.relname AS view_name, pg_get_viewdef(c.oid, true) AS view_definition,
       obj_description(c.oid, 'pg_class') AS view_comment, c.relkind
FROM pg_class c
JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE n.nspname = 'investory' AND c.relkind = 'v'
  AND c.relname IN ('app_v_portfolio_kpi_summary', 'recon_v_portfolio_service_fallback',
                    'recon_v_portfolio_account_quality', 'recon_v_portfolio_data_quality');
CREATE TEMP TABLE _account_stats_dependent_mv_defs AS
SELECT c.relname AS mv_name, pg_get_viewdef(c.oid, true) AS mv_definition,
       obj_description(c.oid, 'pg_class') AS mv_comment
FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE n.nspname = 'investory' AND c.relkind = 'm'
  AND c.relname = 'recon_v_account_statistics_vs_daily';
CREATE TEMP TABLE _account_stats_dependent_indexes AS
SELECT tablename, indexname, indexdef
FROM pg_indexes WHERE schemaname = 'investory'
  AND tablename IN ('recon_v_account_statistics_vs_daily');
DROP VIEW IF EXISTS investory.recon_v_portfolio_data_quality;
DROP VIEW IF EXISTS investory.recon_v_portfolio_account_quality;
DROP VIEW IF EXISTS investory.recon_v_portfolio_service_fallback;
DROP VIEW IF EXISTS investory.app_v_portfolio_kpi_summary;
DROP MATERIALIZED VIEW IF EXISTS investory.recon_v_account_statistics_vs_daily;
DROP MATERIALIZED VIEW IF EXISTS investory.app_v_portfolio_kpi_summary_mv;
DROP VIEW IF EXISTS investory.app_v_account_statistics_reporting;
DROP MATERIALIZED VIEW IF EXISTS investory.app_v_account_statistics;

CREATE MATERIALIZED VIEW investory.app_v_account_statistics AS
WITH latest_daily AS (
    SELECT DISTINCT ON (ad.account_id)
        ad.account_id, ad.snapshot_date, ad.valuation_currency, ad.cash_balance,
        ad.market_value, ad.equity, ad.cost_base, ad.unrealized_profit,
        ad.realized_profit, ad.daily_return_pct
    FROM investory.account_daily ad
    ORDER BY ad.account_id, ad.snapshot_date DESC, ad.id DESC
), latest_daily_in_base AS (
    SELECT ld.account_id, ld.snapshot_date,
        pf.base_currency::varchar(3) AS valuation_currency,
        CASE WHEN investory.fx_status_usable(fx.conversion_status) THEN ld.cash_balance * fx.fx_rate_to_base END AS cash_balance,
        (ld.cash_balance IS NOT NULL AND NOT investory.fx_status_usable(fx.conversion_status)) AS cash_fx_missing,
        CASE WHEN investory.fx_status_usable(fx.conversion_status) THEN ld.market_value * fx.fx_rate_to_base END AS market_value,
        (ld.market_value IS NOT NULL AND NOT investory.fx_status_usable(fx.conversion_status)) AS market_fx_missing,
        CASE WHEN investory.fx_status_usable(fx.conversion_status) THEN ld.equity * fx.fx_rate_to_base END AS equity,
        CASE WHEN investory.fx_status_usable(fx.conversion_status) THEN ld.cost_base * fx.fx_rate_to_base END AS cost_base,
        CASE WHEN investory.fx_status_usable(fx.conversion_status) THEN ld.unrealized_profit * fx.fx_rate_to_base END AS unrealized_profit,
        CASE WHEN investory.fx_status_usable(fx.conversion_status) THEN ld.realized_profit * fx.fx_rate_to_base END AS realized_profit,
        ld.daily_return_pct
    FROM latest_daily ld
    JOIN investory.accounts a ON a.id = ld.account_id
    JOIN investory.portfolios pf ON pf.id = a.portfolio_id
    LEFT JOIN investory.app_v_portfolio_daily_fx_rate_mv fx
      ON fx.portfolio_id = a.portfolio_id
     AND fx.valuation_date = ld.snapshot_date::date
     AND fx.source_currency = ld.valuation_currency::varchar(3)
     AND fx.base_currency = pf.base_currency::varchar(3)
), open_position_totals AS (
    SELECT value.account_id,
        COUNT(*)::bigint AS position_count,
        CASE WHEN COUNT(*) FILTER (WHERE value.cost_basis_in_base_currency IS NOT NULL) = 0 THEN NULL::numeric ELSE SUM(value.cost_basis_in_base_currency) FILTER (WHERE value.cost_basis_in_base_currency IS NOT NULL) END AS cost_base,
        CASE WHEN COUNT(*) FILTER (WHERE value.market_value_in_base_currency IS NOT NULL) = 0 THEN NULL::numeric ELSE SUM(value.market_value_in_base_currency) FILTER (WHERE value.market_value_in_base_currency IS NOT NULL) END AS market_value,
        CASE WHEN COUNT(*) FILTER (WHERE value.cost_basis_in_base_currency IS NOT NULL AND value.market_value_in_base_currency IS NOT NULL) = 0 THEN NULL::numeric ELSE SUM(value.market_value_in_base_currency - value.cost_basis_in_base_currency) FILTER (WHERE value.cost_basis_in_base_currency IS NOT NULL AND value.market_value_in_base_currency IS NOT NULL) END AS unrealized_profit,
        COUNT(*) FILTER (WHERE value.cost_basis_in_base_currency IS NULL OR value.market_value_in_base_currency IS NULL)::bigint AS missing_fx_count
    FROM investory.app_v_current_open_position_rows value
    GROUP BY value.account_id
), closed_position_components AS (
    SELECT a.id AS account_id, a.portfolio_id, p.close_time::date AS valuation_date,
        p.profit_currency::varchar(3) AS source_currency, pf.base_currency::varchar(3) AS base_currency,
        CASE WHEN p.settlement_model = 'RESULT_ONLY' THEN COALESCE(p.profit, 0) ELSE COALESCE(p.profit, 0) + COALESCE(p.swap, 0) END AS amount_native
    FROM investory.positions p
    JOIN investory.accounts a ON a.id = p.account_id
    JOIN investory.portfolios pf ON pf.id = a.portfolio_id
    WHERE p.close_time IS NOT NULL AND p.asset_id IS NOT NULL
    UNION ALL
    SELECT a.id AS account_id, a.portfolio_id, p.close_time::date AS valuation_date,
        p.commission_currency::varchar(3) AS source_currency, pf.base_currency::varchar(3) AS base_currency,
        CASE WHEN p.settlement_model = 'RESULT_ONLY' THEN 0 ELSE COALESCE(p.commission, 0) END AS amount_native
    FROM investory.positions p
    JOIN investory.accounts a ON a.id = p.account_id
    JOIN investory.portfolios pf ON pf.id = a.portfolio_id
    WHERE p.close_time IS NOT NULL AND p.asset_id IS NOT NULL
), closed_position_totals AS (
    SELECT c.account_id,
        CASE WHEN COUNT(*) FILTER (WHERE NOT investory.fx_status_usable(fx.conversion_status)) > 0 THEN NULL::numeric ELSE SUM(c.amount_native * fx.fx_rate_to_target) END AS realized_profit,
        SUM(c.amount_native * fx.fx_rate_to_target) FILTER (WHERE investory.fx_status_usable(fx.conversion_status)) AS converted_subtotal,
        COUNT(*) FILTER (WHERE NOT investory.fx_status_usable(fx.conversion_status))::bigint AS missing_fx_count
    FROM closed_position_components c
    LEFT JOIN LATERAL investory.resolve_fx_rate(
        c.valuation_date,
        c.source_currency,
        c.base_currency
    ) fx ON true
    GROUP BY c.account_id
), portfolio_flow_rows AS (
    SELECT nco.*,
        CASE
            WHEN nco.normalized_category IN ('EXTERNAL_DEPOSIT', 'EXTERNAL_WITHDRAWAL') THEN nco.amount_in_portfolio_base_currency
            WHEN nco.normalized_category = 'INTERNAL_BOOKKEEPING' AND nco.comment ~* 'transfer from [0-9]+ to [0-9]+' AND substring(nco.comment from '(?i)to ([0-9]+)')::bigint = nco.account_id AND nco.amount > 0 AND NOT EXISTS (SELECT 1 FROM investory.accounts counterparty WHERE counterparty.id = substring(nco.comment from '(?i)transfer from ([0-9]+)')::bigint) THEN nco.amount_in_portfolio_base_currency
            WHEN nco.normalized_category = 'INTERNAL_BOOKKEEPING' AND nco.comment ~* 'transfer from [0-9]+ to [0-9]+' AND substring(nco.comment from '(?i)transfer from ([0-9]+)')::bigint = nco.account_id AND nco.amount < 0 AND NOT EXISTS (SELECT 1 FROM investory.accounts counterparty WHERE counterparty.id = substring(nco.comment from '(?i)to ([0-9]+)')::bigint) THEN nco.amount_in_portfolio_base_currency
            ELSE 0::numeric
        END AS scoped_portfolio_flow_amount_in_portfolio_base_currency
    FROM investory.app_v_normalized_cash_operations nco
), flow_totals AS (
    SELECT nco.account_id,
        COUNT(*) FILTER (WHERE NOT investory.fx_status_usable(nco.portfolio_conversion_status) OR NOT investory.fx_status_usable(nco.account_conversion_status))::bigint AS missing_fx_count,
        COUNT(*) FILTER (WHERE NOT investory.fx_status_usable(nco.account_conversion_status))::bigint AS account_missing_fx_count,
        SUM(nco.amount_in_portfolio_base_currency) FILTER (WHERE investory.fx_status_usable(nco.portfolio_conversion_status)) AS converted_subtotal,
        SUM(nco.scoped_portfolio_flow_amount_in_portfolio_base_currency) FILTER (WHERE nco.scoped_portfolio_flow_amount_in_portfolio_base_currency > 0) AS total_deposit,
        SUM(CASE WHEN nco.normalized_category = 'EXTERNAL_DEPOSIT' THEN nco.amount_in_account_currency ELSE NULL::numeric END) AS total_deposit_account_currency,
        SUM(-nco.scoped_portfolio_flow_amount_in_portfolio_base_currency) FILTER (WHERE nco.scoped_portfolio_flow_amount_in_portfolio_base_currency < 0) AS total_withdrawal,
        SUM(CASE WHEN nco.normalized_category = 'EXTERNAL_WITHDRAWAL' THEN ABS(nco.amount_in_account_currency) ELSE NULL::numeric END) AS total_withdrawal_account_currency,
        SUM(CASE WHEN nco.normalized_category IN ('DIVIDEND', 'DIVIDEND_REVERSAL') THEN nco.amount_in_base_currency END) AS dividends,
        SUM(CASE WHEN nco.normalized_category IN ('INTEREST', 'INTEREST_REVERSAL') THEN nco.amount_in_base_currency END) AS interest,
        SUM(CASE WHEN nco.normalized_category = 'FEE' THEN -nco.amount_in_base_currency END) AS fees,
        SUM(CASE WHEN nco.normalized_category IN ('WITHHOLDING_TAX', 'WITHHOLDING_TAX_REVERSAL', 'OTHER_TAX') THEN -nco.amount_in_base_currency END) AS taxes
    FROM portfolio_flow_rows nco GROUP BY nco.account_id
), activity_meta AS (
    SELECT ad.account_id,
        COUNT(*) FILTER (WHERE COALESCE(ad.deposits, 0) <> 0 OR COALESCE(ad.withdrawals, 0) <> 0 OR COALESCE(ad.dividends, 0) <> 0 OR COALESCE(ad.interest, 0) <> 0 OR COALESCE(ad.fees, 0) <> 0 OR COALESCE(ad.taxes, 0) <> 0 OR COALESCE(ad.realized_profit, 0) <> 0)::integer AS activity_count,
        MIN(ad.snapshot_date) FILTER (WHERE COALESCE(ad.deposits, 0) <> 0 OR COALESCE(ad.withdrawals, 0) <> 0 OR COALESCE(ad.dividends, 0) <> 0 OR COALESCE(ad.interest, 0) <> 0 OR COALESCE(ad.fees, 0) <> 0 OR COALESCE(ad.taxes, 0) <> 0 OR COALESCE(ad.realized_profit, 0) <> 0)::timestamptz AS first_activity_at,
        MAX(ad.snapshot_date) FILTER (WHERE COALESCE(ad.deposits, 0) <> 0 OR COALESCE(ad.withdrawals, 0) <> 0 OR COALESCE(ad.dividends, 0) <> 0 OR COALESCE(ad.interest, 0) <> 0 OR COALESCE(ad.fees, 0) <> 0 OR COALESCE(ad.taxes, 0) <> 0 OR COALESCE(ad.realized_profit, 0) <> 0)::timestamptz AS last_activity_at
    FROM investory.account_daily ad GROUP BY ad.account_id
)
SELECT a.id AS account_id, p.base_currency::varchar(3) AS valuation_currency,
    CASE WHEN COALESCE(ft.missing_fx_count, 0) > 0 THEN NULL ELSE COALESCE(ft.total_deposit, 0) END AS total_deposit,
    CASE WHEN COALESCE(ft.missing_fx_count, 0) > 0 THEN NULL ELSE COALESCE(ft.total_withdrawal, 0) END AS total_withdrawal,
    CASE WHEN COALESCE(ft.missing_fx_count, 0) > 0 THEN NULL ELSE COALESCE(ft.total_deposit, 0) - COALESCE(ft.total_withdrawal, 0) END AS net_deposit,
    CASE WHEN COALESCE(ft.account_missing_fx_count, 0) > 0 THEN NULL ELSE COALESCE(ft.total_deposit_account_currency, 0) - COALESCE(ft.total_withdrawal_account_currency, 0) END AS account_net_deposit,
    CASE WHEN COALESCE(ld.cash_fx_missing, false) THEN NULL ELSE COALESCE(ld.cash_balance, 0) END AS cash_balance,
    CASE WHEN COALESCE(ld.market_fx_missing, false) THEN NULL
         WHEN COALESCE(opt.position_count, 0) > 0 THEN opt.market_value
         ELSE COALESCE(ld.market_value, 0) END AS market_value,
    CASE WHEN COALESCE(ld.cash_fx_missing, false) THEN NULL
         WHEN COALESCE(opt.position_count, 0) > 0 THEN
             CASE WHEN opt.market_value IS NULL THEN NULL ELSE COALESCE(ld.cash_balance, 0) + opt.market_value END
         ELSE COALESCE(ld.equity, COALESCE(ld.cash_balance, 0)) END AS equity,
    CASE WHEN COALESCE(opt.position_count, 0) > 0 THEN opt.cost_base ELSE COALESCE(ld.cost_base, 0) END AS cost_base,
    CASE WHEN COALESCE(cpt.missing_fx_count, 0) > 0 THEN NULL ELSE COALESCE(cpt.realized_profit, 0) END AS realized_profit,
    CASE WHEN COALESCE(opt.position_count, 0) > 0 THEN opt.unrealized_profit ELSE COALESCE(ld.unrealized_profit, 0) END AS unrealized_profit,
    CASE WHEN COALESCE(ft.missing_fx_count, 0) > 0 THEN NULL ELSE COALESCE(ft.dividends, 0) END AS dividends,
    CASE WHEN COALESCE(ft.missing_fx_count, 0) > 0 THEN NULL ELSE COALESCE(ft.interest, 0) END AS interest,
    CASE WHEN COALESCE(ft.missing_fx_count, 0) > 0 THEN NULL ELSE COALESCE(ft.fees, 0) END AS fees,
    CASE WHEN COALESCE(ft.missing_fx_count, 0) > 0 THEN NULL ELSE COALESCE(ft.taxes, 0) END AS taxes,
    COALESCE(ft.converted_subtotal, 0) AS converted_cash_subtotal,
    COALESCE(ft.missing_fx_count, 0) + COALESCE(cpt.missing_fx_count, 0) + COALESCE(opt.missing_fx_count, 0)
        + CASE WHEN COALESCE(ld.cash_fx_missing, false) THEN 1 ELSE 0 END
        + CASE WHEN COALESCE(ld.market_fx_missing, false) THEN 1 ELSE 0 END AS missing_fx_count,
    COALESCE(ft.missing_fx_count, 0) = 0 AND COALESCE(cpt.missing_fx_count, 0) = 0
        AND COALESCE(opt.missing_fx_count, 0) = 0 AND NOT COALESCE(ld.cash_fx_missing, false)
        AND NOT COALESCE(ld.market_fx_missing, false) AS is_complete,
    COALESCE(am.activity_count, 0) AS activity_count, am.first_activity_at, am.last_activity_at,
    ld.snapshot_date AS latest_snapshot_date, ld.daily_return_pct AS latest_return_pct, NOW() AS updated_at,
    a.cash_only,
    (abs(COALESCE(ld.cash_balance, 0) + COALESCE(
        CASE WHEN COALESCE(opt.position_count, 0) > 0 THEN opt.market_value ELSE COALESCE(ld.market_value, 0) END,
        0)) >= 50
     OR abs(COALESCE(CASE WHEN COALESCE(ft.missing_fx_count, 0) > 0 THEN NULL ELSE COALESCE(ft.total_deposit, 0) - COALESCE(ft.total_withdrawal, 0) END, 0)) >= 50
     OR abs(COALESCE(CASE WHEN COALESCE(ft.account_missing_fx_count, 0) > 0 THEN NULL ELSE COALESCE(ft.total_deposit_account_currency, 0) - COALESCE(ft.total_withdrawal_account_currency, 0) END, 0)) >= 50) AS is_visible
FROM investory.accounts a JOIN investory.portfolios p ON p.id = a.portfolio_id
LEFT JOIN latest_daily_in_base ld ON ld.account_id = a.id
LEFT JOIN open_position_totals opt ON opt.account_id = a.id
LEFT JOIN flow_totals ft ON ft.account_id = a.id
LEFT JOIN activity_meta am ON am.account_id = a.id
LEFT JOIN closed_position_totals cpt ON cpt.account_id = a.id
WITH DATA;

CREATE UNIQUE INDEX ux_mv_account_statistics_account ON investory.app_v_account_statistics(account_id);

CREATE OR REPLACE VIEW investory.app_v_account_statistics_reporting AS
SELECT * FROM investory.app_v_account_statistics;

COMMENT ON VIEW investory.app_v_account_statistics_reporting IS
  'Compatibility view over canonical portfolio-base account statistics. It is not a selected reporting-currency view.';

CREATE MATERIALIZED VIEW investory.app_v_portfolio_kpi_summary_mv AS
WITH latest_portfolio_daily AS (
    SELECT DISTINCT ON (pd.portfolio_id) pd.portfolio_id, pd.base_currency, pd.snapshot_date,
        pd.cash_balance, pd.market_value, pd.equity, pd.converted_equity_subtotal,
        pd.missing_fx_count, pd.is_complete
    FROM investory.app_v_portfolio_daily pd ORDER BY pd.portfolio_id, pd.snapshot_date DESC
), latest_account_stats AS (
    SELECT a.portfolio_id, SUM(ast.missing_fx_count)::bigint AS missing_fx_count,
        SUM(ast.converted_cash_subtotal) AS converted_cash_subtotal, SUM(ast.cash_balance) AS total_cash,
        SUM(ast.market_value) AS total_market_value, SUM(ast.equity) AS total_equity,
        SUM(ast.total_deposit) AS total_deposits, SUM(ast.total_withdrawal) AS total_withdrawals,
        SUM(ast.total_deposit - ast.total_withdrawal) AS net_deposits,
        SUM(ast.realized_profit) AS total_realized_profit, SUM(ast.unrealized_profit) AS total_unrealized_profit,
        SUM(ast.dividends) AS total_dividends, SUM(ast.interest) AS total_interest,
        SUM(ast.fees) AS total_fees, SUM(ast.taxes) AS total_taxes, SUM(ast.activity_count) AS activity_count,
        MIN(ast.first_activity_at) AS first_activity_at, MAX(ast.last_activity_at) AS last_activity_at
    FROM investory.app_v_account_statistics ast JOIN investory.accounts a ON a.id = ast.account_id
    GROUP BY a.portfolio_id
)
SELECT p.id AS portfolio_id, p.name AS portfolio_name, p.base_currency::varchar(3) AS base_currency,
    CASE WHEN COALESCE(las.missing_fx_count, 0) > 0 THEN NULL ELSE COALESCE(las.total_deposits, 0) END AS total_deposits,
    CASE WHEN COALESCE(las.missing_fx_count, 0) > 0 THEN NULL ELSE COALESCE(las.total_withdrawals, 0) END AS total_withdrawals,
    CASE WHEN COALESCE(las.missing_fx_count, 0) > 0 THEN NULL ELSE COALESCE(las.net_deposits, 0) END AS net_deposits,
    las.total_cash AS total_cash,
    las.total_market_value AS total_market_value,
    las.total_equity AS total_equity,
    las.total_realized_profit AS total_realized_profit,
    las.total_unrealized_profit AS total_unrealized_profit,
    las.total_dividends AS total_dividends,
    las.total_interest AS total_interest,
    las.total_fees AS total_fees,
    las.total_taxes AS total_taxes,
    COALESCE(las.converted_cash_subtotal, 0) AS converted_cash_subtotal, COALESCE(lpd.converted_equity_subtotal, 0) AS converted_equity_subtotal,
    COALESCE(las.missing_fx_count, 0) AS missing_fx_count, COALESCE(las.missing_fx_count, 0) = 0 AS is_complete,
    COALESCE(las.activity_count, 0) AS activity_count, las.first_activity_at, las.last_activity_at,
    lpd.snapshot_date AS source_max_date, NOW() AS updated_at
FROM investory.portfolios p LEFT JOIN latest_portfolio_daily lpd ON lpd.portfolio_id = p.id
LEFT JOIN latest_account_stats las ON las.portfolio_id = p.id
WITH DATA;

CREATE UNIQUE INDEX ux_app_v_portfolio_kpi_summary_mv_portfolio
    ON investory.app_v_portfolio_kpi_summary_mv(portfolio_id);

DO $$
DECLARE v record;
BEGIN
    FOR v IN SELECT * FROM _account_stats_dependent_defs WHERE view_name = 'app_v_portfolio_kpi_summary' LOOP
        EXECUTE 'CREATE VIEW investory.' || quote_ident(v.view_name) || ' AS ' || regexp_replace(v.view_definition, ';[[:space:]]*$', '');
        IF v.view_comment IS NOT NULL THEN EXECUTE 'COMMENT ON VIEW investory.' || quote_ident(v.view_name) || ' IS ' || quote_literal(v.view_comment); END IF;
    END LOOP;
    FOR v IN SELECT * FROM _account_stats_dependent_mv_defs LOOP
        EXECUTE 'CREATE MATERIALIZED VIEW investory.' || quote_ident(v.mv_name) || ' AS ' || regexp_replace(v.mv_definition, ';[[:space:]]*$', '') || ' WITH DATA';
        IF v.mv_comment IS NOT NULL THEN EXECUTE 'COMMENT ON MATERIALIZED VIEW investory.' || quote_ident(v.mv_name) || ' IS ' || quote_literal(v.mv_comment); END IF;
    END LOOP;
    FOR v IN SELECT * FROM _account_stats_dependent_defs
             WHERE view_name IN ('recon_v_portfolio_account_quality', 'recon_v_portfolio_data_quality', 'recon_v_portfolio_service_fallback')
             ORDER BY CASE view_name WHEN 'recon_v_portfolio_account_quality' THEN 1 WHEN 'recon_v_portfolio_data_quality' THEN 2 ELSE 3 END LOOP
        EXECUTE 'CREATE VIEW investory.' || quote_ident(v.view_name) || ' AS ' || regexp_replace(v.view_definition, ';[[:space:]]*$', '');
        IF v.view_comment IS NOT NULL THEN
            EXECUTE 'COMMENT ON VIEW investory.' || quote_ident(v.view_name) || ' IS ' || quote_literal(v.view_comment);
        END IF;
    END LOOP;
    FOR v IN SELECT * FROM _account_stats_dependent_indexes LOOP
        EXECUTE v.indexdef;
    END LOOP;
END
$$;
