SET search_path TO investory, public;

CREATE TABLE investory.notification_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(64) NOT NULL,
    severity VARCHAR(16) NOT NULL,
    portfolio_id BIGINT,
    source_entity_type VARCHAR(64) NOT NULL,
    source_entity_id VARCHAR(128) NOT NULL,
    fingerprint VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL,
    delivery_state VARCHAR(24) NOT NULL DEFAULT 'PENDING',
    delivered_at TIMESTAMPTZ,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    last_attempt_at TIMESTAMPTZ,
    next_attempt_at TIMESTAMPTZ NOT NULL,
    last_error VARCHAR(1000),
    CONSTRAINT uq_notification_event_fingerprint UNIQUE (fingerprint),
    CONSTRAINT ck_notification_event_type CHECK (event_type IN (
        'SYSTEM_AUDIT_ERROR', 'IMPORT_FAILED_OR_PARTIAL', 'PLAN_BECAME_UNSUSTAINABLE')),
    CONSTRAINT ck_notification_event_severity CHECK (severity IN ('WARNING', 'ERROR', 'CRITICAL')),
    CONSTRAINT ck_notification_event_delivery_state CHECK (delivery_state IN (
        'PENDING', 'RETRYABLE', 'DELIVERED', 'EXHAUSTED')),
    CONSTRAINT ck_notification_event_attempt_count CHECK (attempt_count >= 0),
    CONSTRAINT ck_notification_event_delivery_time CHECK (
        (delivery_state = 'DELIVERED' AND delivered_at IS NOT NULL)
        OR (delivery_state <> 'DELIVERED' AND delivered_at IS NULL))
);

CREATE INDEX ix_notification_event_dispatch
    ON investory.notification_event (next_attempt_at, created_at)
    WHERE delivery_state IN ('PENDING', 'RETRYABLE');

CREATE INDEX ix_notification_event_source
    ON investory.notification_event (source_entity_type, source_entity_id);

COMMENT ON TABLE investory.notification_event IS
    'Channel-neutral durable notification outbox. Fingerprints enforce producer idempotency; delivery is retryable and at-least-once.';
