CREATE TABLE investory.retirement_annual_cost_years (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id bigint NOT NULL REFERENCES investory.retirement_plans(id) ON DELETE CASCADE,
    year integer NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_retirement_annual_cost_years_plan_year UNIQUE (plan_id, year)
);

INSERT INTO investory.retirement_annual_cost_years (plan_id, year)
SELECT DISTINCT plan_id, EXTRACT(YEAR FROM CURRENT_DATE)::integer
FROM investory.retirement_annual_cost_groups;

ALTER TABLE investory.retirement_annual_cost_groups
    DROP CONSTRAINT uq_retirement_annual_cost_groups_plan_name,
    ADD COLUMN year_id bigint;

UPDATE investory.retirement_annual_cost_groups cost_group
SET year_id = cost_year.id
FROM investory.retirement_annual_cost_years cost_year
WHERE cost_year.plan_id = cost_group.plan_id
  AND cost_year.year = EXTRACT(YEAR FROM CURRENT_DATE)::integer;

ALTER TABLE investory.retirement_annual_cost_groups
    ALTER COLUMN year_id SET NOT NULL,
    ADD CONSTRAINT fk_retirement_annual_cost_groups_year
        FOREIGN KEY (year_id) REFERENCES investory.retirement_annual_cost_years(id) ON DELETE CASCADE,
    ADD CONSTRAINT uq_retirement_annual_cost_groups_year_name UNIQUE (year_id, name),
    DROP COLUMN plan_id;

CREATE INDEX idx_retirement_annual_cost_groups_year_order
    ON investory.retirement_annual_cost_groups (year_id, sort_order, id);
