CREATE TABLE investory.retirement_annual_cost_groups (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id bigint NOT NULL REFERENCES investory.retirement_plans(id) ON DELETE CASCADE,
    name varchar(120) NOT NULL,
    monthly_amount numeric(19, 2) NOT NULL CHECK (monthly_amount >= 0),
    sort_order integer NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_retirement_annual_cost_groups_plan_name UNIQUE (plan_id, name)
);

CREATE INDEX idx_retirement_annual_cost_groups_plan_order
    ON investory.retirement_annual_cost_groups (plan_id, sort_order, id);
