SET search_path TO investory, public;

-- Canonical retirement storage. A plan is mutable user intent; projections are runtime-only.
CREATE TABLE IF NOT EXISTS investory.retirement_plans (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id bigint NOT NULL REFERENCES investory.portfolios(id) ON DELETE CASCADE,
    name varchar(255) NOT NULL,
    birth_date date,
    effective_year integer NOT NULL,
    end_age integer NOT NULL,
    retirement_age integer,
    annual_employment_income numeric(30,12),
    annual_pre_retirement_contribution numeric(30,12),
    annual_living_expenses numeric(30,12) NOT NULL,
    annual_discretionary_expenses numeric(30,12) NOT NULL,
    inflation_rate numeric(20,12) NOT NULL,
    rental_income_growth_rate numeric(20,12) NOT NULL,
    spending_growth_rate numeric(20,12) NOT NULL,
    funding_strategy varchar(32),
    funding_order varchar(64) NOT NULL DEFAULT 'RESERVE,LONG_TERM,INVESTMENT',
    expense_profile varchar(512),
    safe_reserve_years numeric(20,12) DEFAULT 5,
    equity_harvest_minimum_return_rate numeric(20,12) DEFAULT 0.07,
    equity_gain_harvest_rate numeric(20,12) DEFAULT 0.75,
    allow_emergency_equity_withdrawal boolean DEFAULT false,
    fixed_income_return_rate numeric(20,12) NOT NULL,
    equity_return_rate numeric(20,12) NOT NULL,
    pension_start_age integer NOT NULL,
    annual_pension numeric(30,12) NOT NULL,
    capital_gain_tax_rate numeric(20,12) NOT NULL,
    baseline_as_of_year integer,
    baseline_reserve numeric(30,12),
    baseline_investment_capital numeric(30,12),
    baseline_long_term_capital numeric(30,12),
    baseline_rental_income numeric(30,12),
    baseline_long_term_income numeric(30,12),
    baseline_long_term_state text,
    baseline_long_term_state_version integer,
    archived boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (btrim(name) <> ''),
    UNIQUE (portfolio_id, name)
);

CREATE INDEX IF NOT EXISTS ix_retirement_plans_portfolio
    ON investory.retirement_plans(portfolio_id);

CREATE TABLE IF NOT EXISTS investory.retirement_plan_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id bigint NOT NULL REFERENCES investory.retirement_plans(id) ON DELETE CASCADE,
    event_year integer NOT NULL,
    name varchar(255) NOT NULL,
    amount numeric(30,12) NOT NULL,
    event_type varchar(32) NOT NULL,
    notes varchar(1023),
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_retirement_plan_events_plan_year
    ON investory.retirement_plan_events(plan_id, event_year, id);

CREATE TABLE IF NOT EXISTS investory.retirement_planning_years (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id bigint NOT NULL REFERENCES investory.portfolios(id) ON DELETE CASCADE,
    planning_year integer NOT NULL,
    status varchar(16) NOT NULL,
    state jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (portfolio_id, planning_year)
);

COMMENT ON TABLE investory.retirement_plans IS
    'Mutable persisted retirement intent. Current age and future projections are derived at runtime.';
COMMENT ON TABLE investory.retirement_plan_events IS
    'Mutable plan events. Events are not copied into immutable revision snapshots.';
COMMENT ON TABLE investory.retirement_planning_years IS
    'Persisted historical/reviewed planning state only; generated future projections are not stored.';

-- Forward migration from the legacy model. Keep IDs so canonical fixtures and ownership links remain stable.
INSERT INTO investory.retirement_plans (
    id, portfolio_id, name, birth_date, effective_year, end_age, retirement_age,
    annual_employment_income, annual_pre_retirement_contribution, annual_living_expenses,
    annual_discretionary_expenses, inflation_rate, rental_income_growth_rate,
    spending_growth_rate, funding_strategy, funding_order, expense_profile, safe_reserve_years,
    equity_harvest_minimum_return_rate, equity_gain_harvest_rate, allow_emergency_equity_withdrawal,
    fixed_income_return_rate, equity_return_rate, pension_start_age, annual_pension,
    capital_gain_tax_rate, baseline_as_of_year, baseline_reserve, baseline_investment_capital,
    baseline_long_term_capital, baseline_rental_income, baseline_long_term_income,
    baseline_long_term_state, baseline_long_term_state_version, archived, created_at, updated_at)
SELECT p.id, p.portfolio_id, p.name,
       make_date(r.start_year - r.current_age, 1, 1), r.start_year, r.end_age, r.retirement_age,
       r.annual_employment_income, r.annual_pre_retirement_contribution, r.annual_living_expenses,
       r.annual_discretionary_expenses, r.inflation_rate, r.rental_income_growth_rate,
       r.spending_growth_rate, r.funding_strategy, r.funding_order, r.expense_profile, r.safe_reserve_years,
       r.equity_harvest_minimum_return_rate, r.equity_gain_harvest_rate, r.allow_emergency_equity_withdrawal,
       r.fixed_income_return_rate, r.equity_return_rate, r.pension_start_age, r.annual_pension,
       r.capital_gain_tax_rate, r.baseline_as_of_year, r.baseline_reserve, r.baseline_investment_capital,
       r.baseline_long_term_capital, r.baseline_rental_income, r.baseline_long_term_income,
       r.baseline_long_term_state, r.baseline_long_term_state_version, p.archived,
       p.created_at, p.updated_at
FROM investory.simulation_plans p
JOIN investory.simulation_plan_revisions r
  ON r.id = p.current_revision_id AND r.simulation_plan_id = p.id
WHERE NOT p.sandbox
ON CONFLICT (id) DO NOTHING;

INSERT INTO investory.retirement_plan_events
    (id, plan_id, event_year, name, amount, event_type, notes, created_at)
SELECT e.id, r.simulation_plan_id, e.event_year, e.name, e.amount, e.event_type, e.notes, e.created_at
FROM investory.simulation_plan_revision_events e
JOIN investory.simulation_plan_revisions r ON r.id = e.revision_id
JOIN investory.retirement_plans p ON p.id = r.simulation_plan_id
WHERE r.id = (SELECT current_revision_id FROM investory.simulation_plans WHERE id = r.simulation_plan_id)
ON CONFLICT (id) DO NOTHING;

INSERT INTO investory.retirement_planning_years
    (id, portfolio_id, planning_year, status, state, created_at, updated_at)
SELECT py.id,
       py.portfolio_id,
       py.planning_year,
       py.status,
       jsonb_strip_nulls(jsonb_build_object(
           'baselinePlanId', py.baseline_plan_id,
           'baselineCreatedAt', py.baseline_created_at,
           'closedAt', py.closed_at,
           'reopenedAt', py.reopened_at,
           'values', jsonb_build_object(
               'ACTUAL', COALESCE((
                   SELECT jsonb_object_agg(v.metric, jsonb_strip_nulls(jsonb_build_object(
                       'metric', v.metric,
                       'derivedValue', v.derived_value,
                       'approvedValue', v.approved_value,
                       'source', v.source_type,
                       'note', v.note)))
                   FROM investory.planning_year_values v
                   WHERE v.planning_year_id = py.id AND v.value_kind = 'ACTUAL'), '{}'::jsonb),
               'BASELINE', COALESCE((
                   SELECT jsonb_object_agg(v.metric, jsonb_strip_nulls(jsonb_build_object(
                       'metric', v.metric,
                       'derivedValue', v.derived_value,
                       'approvedValue', v.approved_value,
                       'source', v.source_type,
                       'note', v.note)))
                   FROM investory.planning_year_values v
                   WHERE v.planning_year_id = py.id AND v.value_kind = 'BASELINE'), '{}'::jsonb)))),
       py.created_at,
       py.updated_at
FROM investory.planning_years py
ON CONFLICT (id) DO NOTHING;

SELECT setval(
    pg_get_serial_sequence('investory.retirement_plans', 'id'),
    COALESCE((SELECT MAX(id) FROM investory.retirement_plans), 1),
    true);
SELECT setval(
    pg_get_serial_sequence('investory.retirement_plan_events', 'id'),
    COALESCE((SELECT MAX(id) FROM investory.retirement_plan_events), 1),
    true);
SELECT setval(
    pg_get_serial_sequence('investory.retirement_planning_years', 'id'),
    COALESCE((SELECT MAX(id) FROM investory.retirement_planning_years), 1),
    true);

-- The canonical stores are now populated. Remove the revision and EAV persistence models so
-- application code cannot accidentally keep both paths alive.
DROP TABLE investory.planning_year_values;
DROP TABLE investory.planning_years;
DROP TABLE investory.simulation_plan_revision_events;
ALTER TABLE investory.simulation_plans DROP CONSTRAINT fk_simulation_plans_current_revision;
DROP TABLE investory.simulation_plan_revisions;
DROP TABLE investory.simulation_plans;
