-- Preserve the annual tax-base contract and make the formula explicit without rewriting facts.
COMMENT ON COLUMN investory.real_estate.tax_base IS
    'Annual rental-tax base in asset currency. Annual rental tax = tax_base * 0.085; NULL means unspecified.';

ALTER TABLE investory.bond
    ADD CONSTRAINT ck_bond_maturity_after_acquisition
        CHECK (acquisition_date IS NULL OR maturity_date >= acquisition_date);

ALTER TABLE investory.cash_reserve
    ADD CONSTRAINT ck_cash_reserve_maturity_after_acquisition
        CHECK (acquisition_date IS NULL OR maturity_date IS NULL OR maturity_date >= acquisition_date);

ALTER TABLE investory.rental_contract
    ADD CONSTRAINT ck_rental_contract_termination_before_expected_end
        CHECK (terminated_date IS NULL OR end_date IS NULL OR terminated_date <= end_date);

-- Historical availability must be proven. Existing assets are deliberately not backfilled because
-- archived_at alone cannot show whether an asset was previously archived and reactivated.
CREATE TABLE investory.long_term_asset_history (
    asset_id bigint PRIMARY KEY,
    asset_type varchar(32) NOT NULL,
    complete boolean NOT NULL DEFAULT false,
    CONSTRAINT ck_long_term_asset_history_type
        CHECK (asset_type IN ('REAL_ESTATE', 'BOND', 'CASH_RESERVE', 'PERSONAL_ASSET'))
);

CREATE TABLE investory.long_term_asset_archive_interval (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id bigint NOT NULL
        REFERENCES investory.long_term_asset_history(asset_id),
    archived_from date NOT NULL,
    archived_to date,
    CONSTRAINT ck_long_term_asset_archive_interval_dates
        CHECK (archived_to IS NULL OR archived_to >= archived_from)
);

CREATE UNIQUE INDEX uq_long_term_asset_archive_interval_open
    ON investory.long_term_asset_archive_interval(asset_id)
    WHERE archived_to IS NULL;
