SET search_path TO investory, public;

CREATE TABLE IF NOT EXISTS investory.simulation_plans (
    id bigserial PRIMARY KEY,
    portfolio_id bigint NOT NULL REFERENCES investory.portfolios(id) ON DELETE CASCADE,
    name varchar(255) NOT NULL,
    current_revision_id bigint,
    archived boolean NOT NULL DEFAULT false,
    sandbox boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (btrim(name) <> ''),
    UNIQUE (portfolio_id, name)
);

CREATE INDEX IF NOT EXISTS ix_simulation_plans_portfolio ON investory.simulation_plans(portfolio_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_simulation_plans_one_sandbox_per_portfolio
    ON investory.simulation_plans (portfolio_id)
    WHERE sandbox AND NOT archived;

CREATE TABLE IF NOT EXISTS investory.simulation_plan_revisions (
    id bigserial PRIMARY KEY,
    simulation_plan_id bigint NOT NULL REFERENCES investory.simulation_plans(id) ON DELETE RESTRICT,
    revision_number integer NOT NULL CHECK (revision_number > 0),
    current_age integer NOT NULL,
    start_year integer NOT NULL,
    end_age integer NOT NULL,
    retirement_age integer,
    annual_employment_income numeric(30,12),
    annual_pre_retirement_contribution numeric(30,12),
    annual_living_expenses numeric(30,12) NOT NULL,
    annual_discretionary_expenses numeric(30,12) NOT NULL,
    inflation_rate numeric(20,12) NOT NULL,
    rental_income_growth_rate numeric(20,12) NOT NULL,
    spending_growth_rate numeric(20,12) NOT NULL,
    funding_strategy varchar(32),
    funding_order varchar(64) NOT NULL DEFAULT 'RESERVE,LONG_TERM,INVESTMENT',
    expense_profile varchar(512),
    safe_reserve_years numeric(20,12) DEFAULT 5,
    equity_harvest_minimum_return_rate numeric(20,12) DEFAULT 0.07,
    equity_gain_harvest_rate numeric(20,12) DEFAULT 0.75,
    allow_emergency_equity_withdrawal boolean DEFAULT false,
    fixed_income_return_rate numeric(20,12) NOT NULL,
    equity_return_rate numeric(20,12) NOT NULL,
    pension_start_age integer NOT NULL,
    annual_pension numeric(30,12) NOT NULL,
    capital_gain_tax_rate numeric(20,12) NOT NULL,
    baseline_as_of_year integer,
    baseline_reserve numeric(30,12),
    baseline_investment_capital numeric(30,12),
    baseline_long_term_capital numeric(30,12),
    baseline_rental_income numeric(30,12),
    baseline_long_term_income numeric(30,12),
    baseline_long_term_state text,
    baseline_long_term_state_version integer,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_simulation_plan_revisions_plan_number
        UNIQUE (simulation_plan_id, revision_number),
    CONSTRAINT uq_simulation_plan_revisions_id_plan
        UNIQUE (id, simulation_plan_id)
);

COMMENT ON TABLE investory.simulation_plan_revisions IS
    'Immutable Base assumption snapshots. Editing a logical plan creates a new revision.';
COMMENT ON COLUMN investory.simulation_plan_revisions.baseline_as_of_year IS
    'As-of year for the frozen economic planning baseline; null means legacy revision.';

ALTER TABLE investory.simulation_plans
    ADD CONSTRAINT fk_simulation_plans_current_revision
        FOREIGN KEY (current_revision_id, id)
        REFERENCES investory.simulation_plan_revisions (id, simulation_plan_id);

CREATE TABLE IF NOT EXISTS investory.simulation_plan_revision_events (
    id bigserial PRIMARY KEY,
    logical_event_id bigint,
    revision_id bigint NOT NULL REFERENCES investory.simulation_plan_revisions(id) ON DELETE RESTRICT,
    event_year integer NOT NULL,
    name varchar(255) NOT NULL,
    amount numeric(30,12) NOT NULL,
    event_type varchar(32) NOT NULL,
    notes varchar(1023),
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_simulation_plan_revision_events_revision_year
    ON investory.simulation_plan_revision_events(revision_id, event_year, id);
CREATE INDEX IF NOT EXISTS ix_simulation_plan_revision_events_logical_id
    ON investory.simulation_plan_revision_events(logical_event_id);

COMMENT ON TABLE investory.simulation_plan_revision_events IS
    'Immutable life-event snapshots owned by a simulation plan revision.';
COMMENT ON COLUMN investory.simulation_plan_revision_events.logical_event_id IS
    'Stable logical event identity copied across immutable plan revisions; null only for legacy rows.';

CREATE TABLE IF NOT EXISTS investory.planning_years (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id bigint NOT NULL REFERENCES investory.portfolios(id) ON DELETE CASCADE,
    planning_year integer NOT NULL,
    status varchar(16) NOT NULL,
    baseline_plan_id bigint,
    baseline_revision_id bigint,
    baseline_created_at timestamptz,
    closed_at timestamptz,
    reopened_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_planning_years_portfolio_year UNIQUE (portfolio_id, planning_year),
    CONSTRAINT ck_planning_years_baseline_revision_pair
        CHECK ((baseline_plan_id IS NULL) = (baseline_revision_id IS NULL)),
    CONSTRAINT fk_planning_years_baseline_revision
        FOREIGN KEY (baseline_revision_id, baseline_plan_id)
        REFERENCES investory.simulation_plan_revisions (id, simulation_plan_id)
);

CREATE TABLE IF NOT EXISTS investory.planning_year_values (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    planning_year_id bigint NOT NULL REFERENCES investory.planning_years(id) ON DELETE CASCADE,
    value_kind varchar(16) NOT NULL,
    metric varchar(48) NOT NULL,
    derived_value numeric(30,12),
    approved_value numeric(30,12),
    source_type varchar(32) NOT NULL,
    note varchar(1000),
    captured_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_planning_year_values_key UNIQUE (planning_year_id, value_kind, metric)
);

COMMENT ON TABLE investory.planning_years IS
    'Planning-only annual lifecycle and expectation baseline. It is downstream from accounting.';
COMMENT ON COLUMN investory.planning_years.baseline_revision_id IS
    'Exact immutable plan revision used to create this baseline; null only for legacy/unmapped data.';
COMMENT ON TABLE investory.planning_year_values IS
    'Planning-only derived, approved, and baseline values. Never an accounting fact table.';

CREATE SEQUENCE investory.long_term_asset_id_seq;

CREATE TABLE investory.bond (
    id bigint PRIMARY KEY DEFAULT nextval('investory.long_term_asset_id_seq'),
    portfolio_id bigint NOT NULL REFERENCES investory.portfolios(id) ON DELETE CASCADE,
    name varchar(255) NOT NULL,
    currency varchar(3) NOT NULL REFERENCES investory.currencies(id),
    value numeric(30,12) NOT NULL CHECK (value >= 0),
    acquisition_date date,
    interest_rate numeric(20,12) NOT NULL CHECK (interest_rate >= 0),
    maturity_date date NOT NULL,
    archived_at date,
    notes text,
    external_key varchar(128),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (btrim(name) <> '')
);
CREATE INDEX ix_bond_portfolio_active ON investory.bond(portfolio_id, archived_at);
CREATE UNIQUE INDEX ux_bond_portfolio_external_key ON investory.bond(portfolio_id, external_key)
    WHERE external_key IS NOT NULL;

CREATE TABLE investory.real_estate (
    id bigint PRIMARY KEY DEFAULT nextval('investory.long_term_asset_id_seq'),
    portfolio_id bigint NOT NULL REFERENCES investory.portfolios(id) ON DELETE CASCADE,
    name varchar(255) NOT NULL,
    currency varchar(3) NOT NULL REFERENCES investory.currencies(id),
    value numeric(30,12) NOT NULL CHECK (value >= 0),
    tax_base numeric(30,12) CHECK (tax_base IS NULL OR tax_base >= 0),
    acquisition_date date,
    land_register_number varchar(128),
    archived_at date,
    notes text,
    external_key varchar(128),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (btrim(name) <> '')
);
CREATE INDEX ix_real_estate_portfolio_active ON investory.real_estate(portfolio_id, archived_at);
COMMENT ON COLUMN investory.real_estate.tax_base IS
    'Annual rental-tax base. Annual rental tax = tax_base * 0.085.';
CREATE UNIQUE INDEX ux_real_estate_portfolio_land_register
    ON investory.real_estate(portfolio_id, land_register_number)
    WHERE land_register_number IS NOT NULL AND btrim(land_register_number) <> '';
CREATE UNIQUE INDEX ux_real_estate_portfolio_external_key ON investory.real_estate(portfolio_id, external_key)
    WHERE external_key IS NOT NULL;

CREATE TABLE investory.cash_reserve (
    id bigint PRIMARY KEY DEFAULT nextval('investory.long_term_asset_id_seq'),
    portfolio_id bigint NOT NULL REFERENCES investory.portfolios(id) ON DELETE CASCADE,
    name varchar(255) NOT NULL,
    currency varchar(3) NOT NULL REFERENCES investory.currencies(id),
    value numeric(30,12) NOT NULL CHECK (value >= 0),
    acquisition_date date,
    interest_rate numeric(20,12) NOT NULL DEFAULT 0 CHECK (interest_rate >= 0),
    maturity_date date,
    archived_at date,
    notes text,
    external_key varchar(128),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (btrim(name) <> '')
);
CREATE INDEX ix_cash_reserve_portfolio_active ON investory.cash_reserve(portfolio_id, archived_at);
CREATE UNIQUE INDEX ux_cash_reserve_portfolio_external_key ON investory.cash_reserve(portfolio_id, external_key)
    WHERE external_key IS NOT NULL;

CREATE TABLE investory.personal_asset (
    id bigint PRIMARY KEY DEFAULT nextval('investory.long_term_asset_id_seq'),
    portfolio_id bigint NOT NULL REFERENCES investory.portfolios(id) ON DELETE CASCADE,
    name varchar(255) NOT NULL,
    category varchar(16) NOT NULL CHECK (category IN ('HOME', 'VEHICLE', 'OTHER')),
    currency varchar(3) NOT NULL REFERENCES investory.currencies(id),
    value numeric(30,12) NOT NULL CHECK (value >= 0),
    acquisition_date date,
    archived_at date,
    notes text,
    external_key varchar(128),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (btrim(name) <> '')
);
CREATE INDEX ix_personal_asset_portfolio_active ON investory.personal_asset(portfolio_id, archived_at);
CREATE UNIQUE INDEX ux_personal_asset_portfolio_external_key ON investory.personal_asset(portfolio_id, external_key)
    WHERE external_key IS NOT NULL;

CREATE TABLE investory.rental_contract (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    real_estate_id bigint NOT NULL REFERENCES investory.real_estate(id) ON DELETE CASCADE,
    start_date date NOT NULL,
    end_date date,
    terminated_date date,
    bootstrap_managed boolean NOT NULL DEFAULT false,
    tenant_name varchar(200),
    tenant_email varchar(320),
    tenant_phone varchar(50),
    notes text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (end_date IS NULL OR end_date >= start_date),
    CHECK (terminated_date IS NULL OR terminated_date >= start_date)
);
CREATE INDEX ix_rental_contract_real_estate_dates ON investory.rental_contract(real_estate_id, start_date DESC);

CREATE TABLE investory.rental_contract_term (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rental_contract_id bigint NOT NULL REFERENCES investory.rental_contract(id) ON DELETE CASCADE,
    cash_flow_type varchar(32) NOT NULL CHECK (cash_flow_type IN
        ('RENT', 'PARKING_RENT', 'ADMIN_FEE', 'UTILITIES', 'PROPERTY_TAX', 'INSURANCE', 'OTHER_INCOME', 'OTHER_EXPENSE')),
    amount numeric(30,12) NOT NULL CHECK (amount >= 0),
    frequency varchar(16) NOT NULL CHECK (frequency IN ('MONTHLY', 'ANNUAL')),
    paid_by_tenant boolean NOT NULL DEFAULT false,
    UNIQUE (rental_contract_id, cash_flow_type)
);
CREATE INDEX ix_rental_contract_term_contract ON investory.rental_contract_term(rental_contract_id, cash_flow_type);

CREATE TABLE investory.real_estate_valuation (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    real_estate_id bigint NOT NULL REFERENCES investory.real_estate(id) ON DELETE CASCADE,
    valuation_date date NOT NULL,
    value numeric(30,12) NOT NULL CHECK (value >= 0),
    UNIQUE (real_estate_id, valuation_date)
);
CREATE INDEX ix_real_estate_valuation_dates ON investory.real_estate_valuation(real_estate_id, valuation_date DESC);

SELECT setval('investory.rental_contract_id_seq', COALESCE((SELECT max(id) FROM investory.rental_contract), 1),
             EXISTS (SELECT 1 FROM investory.rental_contract));
SELECT setval('investory.rental_contract_term_id_seq', COALESCE((SELECT max(id) FROM investory.rental_contract_term), 1),
             EXISTS (SELECT 1 FROM investory.rental_contract_term));
SELECT setval('investory.real_estate_valuation_id_seq', COALESCE((SELECT max(id) FROM investory.real_estate_valuation), 1),
             EXISTS (SELECT 1 FROM investory.real_estate_valuation));

CREATE VIEW investory.app_v_long_term_assets AS
SELECT id, portfolio_id, 'BOND' AS asset_type, name, currency, value AS current_value, acquisition_date, archived_at FROM investory.bond
UNION ALL SELECT id, portfolio_id, 'REAL_ESTATE', name, currency, value, acquisition_date, archived_at FROM investory.real_estate
UNION ALL SELECT id, portfolio_id, 'CASH_RESERVE', name, currency, value, acquisition_date, archived_at FROM investory.cash_reserve
UNION ALL SELECT id, portfolio_id, 'PERSONAL_ASSET', name, currency, value, acquisition_date, archived_at FROM investory.personal_asset;

CREATE VIEW investory.recon_v_long_term_assets AS
WITH asset_ids AS (
    SELECT id, portfolio_id FROM investory.real_estate
    UNION ALL SELECT id, portfolio_id FROM investory.bond
    UNION ALL SELECT id, portfolio_id FROM investory.cash_reserve
    UNION ALL SELECT id, portfolio_id FROM investory.personal_asset
), duplicate_ids AS (
    SELECT id, min(portfolio_id) AS portfolio_id, count(*) AS occurrences
    FROM asset_ids GROUP BY id HAVING count(*) > 1
), orphan_contracts AS (
    SELECT c.id, c.real_estate_id AS asset_id FROM investory.rental_contract c
    WHERE NOT EXISTS (SELECT 1 FROM investory.real_estate r WHERE r.id = c.real_estate_id)
)
SELECT 'LT_ASSET_ID_COLLISION' AS issue_code, id AS asset_id, portfolio_id,
       'same id occurs in multiple explicit asset tables' AS details FROM duplicate_ids
UNION ALL
SELECT 'LT_RENTAL_CONTRACT_ORPHAN', asset_id, NULL::bigint,
       'rental contract has no real-estate parent' FROM orphan_contracts;

COMMENT ON VIEW investory.recon_v_long_term_assets IS
    'Narrow structural diagnostics for explicit Long-Term asset persistence; contains no financial calculations.';
