package com.smartbox.investory.retirement.api.model;

import java.math.BigDecimal;
import java.util.List;

/** Stable public preview returned by the retirement plan editor boundary. */
public record PlanEditorPreview(
    int planStartYear,
    int ageAtPlanStart,
    int currentPlanningYear,
    int currentPlanningAge,
    int projectionStartYear,
    int retirementYear,
    int yearsUntilRetirement,
    int endYear,
    int endAge,
    int planHorizonYears,
    BigDecimal inflationRate,
    BigDecimal rentalIncomeGrowthSpread,
    BigDecimal effectiveRentalIncomeGrowthRate,
    BigDecimal spendingGrowthSpread,
    BigDecimal effectiveSpendingGrowthRate,
    BigDecimal monthlyLivingCosts,
    BigDecimal annualLivingCosts,
    BigDecimal annualExtras,
    BigDecimal totalAnnualCosts,
    BigDecimal nextYearCosts,
    BigDecimal rentalIncome,
    BigDecimal bondIncome,
    Integer plannedIncomeReferenceYear,
    BigDecimal plannedRentalIncome,
    BigDecimal plannedBondIncome,
    BigDecimal plannedInvestmentProfit,
    BigDecimal plannedCapitalizedBondReturn,
    BigDecimal plannedPension,
    BigDecimal plannedAnnualIncome,
    SimulationAssumptions assumptions,
    Integer firstFailureAge,
    List<PreviewYear> years,
    PreviewYear firstProjectedYear) {

  /** Canonical annual preview facts; null means the source has no value for that year. */
  public record PreviewYear(
      int year,
      int age,
      String state,
      String lifecycle,
      BigDecimal recurringCosts,
      BigDecimal eventExpenses,
      BigDecimal totalCosts,
      BigDecimal spendingGrowthRate,
      BigDecimal expenseProfile,
      BigDecimal employmentIncome,
      BigDecimal rentalIncome,
      BigDecimal bondIncome,
      BigDecimal investmentReturn,
      BigDecimal capitalizedBondReturn,
      BigDecimal pension,
      BigDecimal eventIncome,
      BigDecimal totalIncome,
      BigDecimal fundingGap,
      BigDecimal surplus,
      BigDecimal reserveStart,
      BigDecimal reserveTransfer,
      BigDecimal reserveWithdrawal,
      BigDecimal reserveEnd,
      BigDecimal longTermFunding,
      BigDecimal longTermEnd,
      BigDecimal investmentStart,
      BigDecimal investmentReturnForBalance,
      BigDecimal investmentWithdrawal,
      BigDecimal investmentEnd,
      BigDecimal unfunded,
      String status) {}
}
