###
GET {{host}}/export/generate
Content-Type: multipart/form-data; boundary=WebAppBoundary
#Authorization: Basic admin change-me-admin
Authorization: Basic {{user}} {{password}}

###
### Upload IBKR transactions CSV (POST requires ROLE_ADMIN)
###
POST {{host}}/import/broker/ibkr
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Basic {{user}} {{password}}

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="U17959259.TRANSACTIONS.20250211.20260612.csv"
Content-Type: text/csv

< D:\projects\investory\src\main\resources\U17959259.TRANSACTIONS.20250211.20260612.csv
--WebAppBoundary--
