package com.smartbox.investory.accounting.staging;

public enum StagingReasonCode {
  REFERENCE_MISMATCH,
  DATE_MISMATCH,
  COUNTERPARTY_MISMATCH,
  CURRENCY_MISMATCH,
  NET_MISMATCH,
  VAT_MISMATCH,
  GROSS_MISMATCH,
  VAT_TREATMENT_MISMATCH,
  EXTERNAL_ID_MISMATCH,
  BOOKING_DATE_MISMATCH,
  AMOUNT_MISMATCH,
  DUPLICATE,
  MULTIPLE_CANONICAL_MATCHES
}
