#!/usr/bin/env bash
set -euo pipefail

COMPOSE_FILE="${COMPOSE_FILE:-.devcontainer/compose.yml}"
DB_SERVICE="${DB_SERVICE:-db}"
DB_USER="${DB_USER:-investory}"
SNAPSHOT_DB="${SNAPSHOT_DB:-investory_snapshot}"
MIGRATION_DIR="app/src/main/resources/sql/migration"
CONTAINER_MIGRATION_DIR="/tmp/investory-snapshot-migrations"
OUTPUT="test-support/src/main/resources/db/snapshot/schema.sql"
POC_OUTPUT="test-support/src/main/resources/db/snapshot/accounting/poc.sql"
COMMON_DATA_FILE="test-support/src/main/resources/db/snapshot/happyinvestor-common.sql"
BROKER_DATA_FILE="test-support/src/main/resources/db/snapshot/happyinvestor-broker.sql"
CONTAINER_COMMON_DATA_FILE="/tmp/investory-happyinvestor-common.sql"
CONTAINER_BROKER_DATA_FILE="/tmp/investory-happyinvestor-broker.sql"

compose() {
  docker compose -f "$COMPOSE_FILE" "$@"
}

cleanup() {
  compose exec -T "$DB_SERVICE" dropdb --if-exists --username="$DB_USER" "$SNAPSHOT_DB" >/dev/null 2>&1 || true
  compose exec -T "$DB_SERVICE" rm -rf "$CONTAINER_MIGRATION_DIR" >/dev/null 2>&1 || true
  compose exec -T "$DB_SERVICE" rm -f "$CONTAINER_COMMON_DATA_FILE" "$CONTAINER_BROKER_DATA_FILE" >/dev/null 2>&1 || true
}

trap cleanup EXIT

mkdir -p "$(dirname "$OUTPUT")"
compose up -d "$DB_SERVICE"

compose exec -T "$DB_SERVICE" dropdb --if-exists --username="$DB_USER" "$SNAPSHOT_DB"
compose exec -T "$DB_SERVICE" createdb --username="$DB_USER" "$SNAPSHOT_DB"
compose exec -T "$DB_SERVICE" mkdir -p "$CONTAINER_MIGRATION_DIR"
compose cp "$MIGRATION_DIR/." "$DB_SERVICE:$CONTAINER_MIGRATION_DIR"
compose cp "$COMMON_DATA_FILE" "$DB_SERVICE:$CONTAINER_COMMON_DATA_FILE"
compose cp "$BROKER_DATA_FILE" "$DB_SERVICE:$CONTAINER_BROKER_DATA_FILE"

compose exec -T "$DB_SERVICE" sh -ceu "
  for migration in \$(find '$CONTAINER_MIGRATION_DIR' -maxdepth 1 -type f -name '*.sql' | sort); do
    echo \"Applying \$migration\"
    psql -v ON_ERROR_STOP=1 --username='$DB_USER' --dbname='$SNAPSHOT_DB' --file=\"\$migration\"
  done
  psql -v ON_ERROR_STOP=1 --username='$DB_USER' --dbname='$SNAPSHOT_DB' --file='$CONTAINER_COMMON_DATA_FILE'
  psql -v ON_ERROR_STOP=1 --username='$DB_USER' --dbname='$SNAPSHOT_DB' --file='$CONTAINER_BROKER_DATA_FILE'
  psql -v ON_ERROR_STOP=1 --username='$DB_USER' --dbname='$SNAPSHOT_DB' --command=\"SELECT investory.refresh_app_views(); SELECT investory.refresh_reconstructed_position_daily(); SELECT investory.refresh_reconstructed_account_market_daily(); SELECT investory.refresh_reconstructed_cash_daily(); SELECT investory.refresh_account_daily_reconciliation(); SELECT investory.refresh_reconciliation_reporting_views();\"
"

{
  echo "-- Generated by scripts/update-test-db-snapshot.sh. Do not edit manually."
  echo "-- Source: clean PostgreSQL database initialized from app/src/main/resources/sql/migration."
  echo "CREATE EXTENSION IF NOT EXISTS btree_gist;"
  compose exec -T "$DB_SERVICE" pg_dump \
    --username="$DB_USER" \
    --dbname="$SNAPSHOT_DB" \
    --schema=investory \
    --exclude-table='investory.accounting_poc_*' \
    --format=plain \
    --no-owner \
    --no-privileges
} | sed '/^REFRESH MATERIALIZED VIEW /d' | awk '
  # The shared snapshot excludes accounting_poc_* tables. pg_dump still emits
  # foreign keys on retained tables that point at those excluded tables, which
  # makes the snapshot fail before the isolated POC snapshot can be loaded.
  /^-- Name: accounting_vat_transaction accounting_vat_transaction_(expense_invoice_id|invoice_id)_fkey;/ {
    skip = 1
  }
  skip && /^-- Name: / && $0 !~ /accounting_vat_transaction_(expense_invoice_id|invoice_id)_fkey;/ {
    skip = 0
  }
  !skip { print }
' > "$OUTPUT"

# pg_dump emits materialized-view refreshes in object/OID order, which is not
# dependency order. Replay the dependency-aware initial population pipeline
# after all schema and data have been restored. These first refreshes must not be
# concurrent because pg_dump restores materialized views WITH NO DATA.
cat >> "$OUTPUT" <<'SQL'

-- Refresh materialized views in dependency order after snapshot restore.
REFRESH MATERIALIZED VIEW investory.app_v_canonical_asset_daily_price_mv;
REFRESH MATERIALIZED VIEW investory.app_v_canonical_asset_daily_price_ranked_mv;
REFRESH MATERIALIZED VIEW investory.app_v_normalized_daily_price_mv;
REFRESH MATERIALIZED VIEW investory.app_v_current_asset_price_mv;
REFRESH MATERIALIZED VIEW investory.app_v_portfolio_daily_fx_rate_mv;
REFRESH MATERIALIZED VIEW investory.app_v_normalized_cash_operations;
REFRESH MATERIALIZED VIEW investory.app_v_account_monthly;
REFRESH MATERIALIZED VIEW investory.app_v_portfolio_monthly;
REFRESH MATERIALIZED VIEW investory.app_v_account_statistics;
REFRESH MATERIALIZED VIEW investory.app_v_portfolio_contribution_summary_mv;
REFRESH MATERIALIZED VIEW investory.app_v_portfolio_currency_breakdown;
REFRESH MATERIALIZED VIEW investory.app_v_portfolio_asset_allocation;
REFRESH MATERIALIZED VIEW investory.app_v_symbol_performance;
REFRESH MATERIALIZED VIEW investory.app_v_portfolio_kpi_summary_mv;
REFRESH MATERIALIZED VIEW investory.recon_v_reconstructed_position_daily_mv;
REFRESH MATERIALIZED VIEW investory.recon_v_reconstructed_account_market_daily_mv;
REFRESH MATERIALIZED VIEW investory.recon_v_reconstructed_cash_daily_mv;
REFRESH MATERIALIZED VIEW investory.recon_v_account_daily_reconciliation_mv;
REFRESH MATERIALIZED VIEW investory.recon_v_account_monthly_profit;
REFRESH MATERIALIZED VIEW investory.recon_v_account_statistics_vs_daily;
REFRESH MATERIALIZED VIEW investory.recon_v_trade_settlement;
SQL

# PostgreSQL 17 emits client-session guards that are not needed in a committed test fixture.
sed -i.bak '/^\\restrict /d; /^\\unrestrict /d' "$OUTPUT"
rm -f "$OUTPUT.bak"

{
  echo "-- Generated by scripts/update-test-db-snapshot.sh. Do not edit manually."
  echo "-- Source: accounting POC tables and fixtures from the squashed app/src/main/resources/sql/migration/V01.010__accounting_poc_facts.sql."
  compose exec -T "$DB_SERVICE" pg_dump \
    --username="$DB_USER" \
    --dbname="$SNAPSHOT_DB" \
    --schema=investory \
    --table='investory.accounting_poc_*' \
    --format=plain \
    --no-owner \
    --no-privileges
} | sed '/^REFRESH MATERIALIZED VIEW /d' > "$POC_OUTPUT"

# PostgreSQL 17 emits client-session guards that are not needed in a committed test fixture.
sed -i.bak '/^\\restrict /d; /^\\unrestrict /d' "$POC_OUTPUT"
rm -f "$POC_OUTPUT.bak"

echo "Updated $OUTPUT and $POC_OUTPUT"
