#!/usr/bin/env bash
set -euo pipefail

COMPOSE_FILE="${COMPOSE_FILE:-.devcontainer/compose.yml}"
DB_SERVICE="${DB_SERVICE:-db}"
DB_USER="${DB_USER:-investory}"
SNAPSHOT_DB="${SNAPSHOT_DB:-investory_snapshot}"
MIGRATION_DIR="src/main/resources/sql/migration"
CONTAINER_MIGRATION_DIR="/tmp/investory-snapshot-migrations"
OUTPUT="src/test/resources/db/snapshot/schema.sql"

compose() {
  docker compose -f "$COMPOSE_FILE" "$@"
}

cleanup() {
  compose exec -T "$DB_SERVICE" dropdb --if-exists --username="$DB_USER" "$SNAPSHOT_DB" >/dev/null 2>&1 || true
  compose exec -T "$DB_SERVICE" rm -rf "$CONTAINER_MIGRATION_DIR" >/dev/null 2>&1 || true
}

trap cleanup EXIT

mkdir -p "$(dirname "$OUTPUT")"
compose up -d "$DB_SERVICE"

compose exec -T "$DB_SERVICE" dropdb --if-exists --username="$DB_USER" "$SNAPSHOT_DB"
compose exec -T "$DB_SERVICE" createdb --username="$DB_USER" "$SNAPSHOT_DB"
compose exec -T "$DB_SERVICE" mkdir -p "$CONTAINER_MIGRATION_DIR"
compose cp "$MIGRATION_DIR/." "$DB_SERVICE:$CONTAINER_MIGRATION_DIR"

compose exec -T "$DB_SERVICE" sh -ceu "
  for migration in \$(find '$CONTAINER_MIGRATION_DIR' -maxdepth 1 -type f -name '*.sql' | sort); do
    echo \"Applying \$migration\"
    psql -v ON_ERROR_STOP=1 --username='$DB_USER' --dbname='$SNAPSHOT_DB' --file=\"\$migration\"
  done
"

{
  echo "-- Generated by scripts/update-test-db-snapshot.sh. Do not edit manually."
  echo "-- Source: clean PostgreSQL database initialized from src/main/resources/sql/migration."
  compose exec -T "$DB_SERVICE" pg_dump \
    --username="$DB_USER" \
    --dbname="$SNAPSHOT_DB" \
    --schema=investory \
    --format=plain \
    --no-owner \
    --no-privileges
} > "$OUTPUT"

# PostgreSQL 17 emits client-session guards that are not needed in a committed test fixture.
sed -i.bak '/^\\restrict /d; /^\\unrestrict /d' "$OUTPUT"
rm -f "$OUTPUT.bak"

echo "Updated $OUTPUT"
