SET search_path TO investory, public;

INSERT INTO investory.portfolios (id, name, base_currency, owner) VALUES
    (1, 'Alex & Olga Portfolio', 'USD', 'Alex & Olga Kotik')
on conflict do nothing;

SELECT setval(
    pg_get_serial_sequence('investory.portfolios', 'id'),
    COALESCE((SELECT MAX(id) FROM investory.portfolios), 1),
    true
);

insert into accounts (id, currency, provider, name, owner, portfolio_id, cash_only) values
    ('51551301', 'PLN', 'XTB', 'IKE Alex',  'Alex Kotik', 1, false),
    ('51822121', 'USD', 'XTB', 'REITs USD',   'Olga Kotik', 1, false),
    ('51747407', 'EUR', 'XTB', 'EUR - Empty',   'Olga Kotik', 1, true),
    ('53582946', 'USD', 'XTB', 'Trading USD Metal',   'Olga Kotik', 1, false),
    ('51729109', 'PLN', 'XTB', 'IKE Olga',  'Olga Kotik', 1, false),
    ('50290466', 'PLN', 'XTB', 'PLN - Empty',   'Alex Kotik', 1, true),
    ('51499241', 'USD', 'XTB', 'Trading USD',   'Alex Kotik', 1, false),
    ('51548444', 'EUR', 'XTB', 'Trading EUR',   'Alex Kotik', 1, true),
    ('51993106', 'USD', 'XTB', 'Dividends', 'Alex Kotik', 1, false),
    ('51707603', 'PLN', 'XTB', 'PLN - Empty',  'Olga Kotik', 1, true),
    ('17959259', 'USD', 'IBKR', 'IBKR', 'Alex Kotik', 1, false)
on conflict (id) do nothing;

INSERT INTO investory.exchange_rates (month, base, to_currency, rate) VALUES
    ('2024-08-01', 'EUR', 'USD', 1.0820), ('2024-09-01', 'EUR', 'USD', 1.1050), ('2024-10-01', 'EUR', 'USD', 1.1120),
    ('2024-11-01', 'EUR', 'USD', 1.0880), ('2024-12-01', 'EUR', 'USD', 1.0550), ('2025-01-01', 'EUR', 'USD', 1.0350),
    ('2025-02-01', 'EUR', 'USD', 1.0380), ('2025-03-01', 'EUR', 'USD', 1.0620), ('2025-04-01', 'EUR', 'USD', 1.0850),
    ('2025-05-01', 'EUR', 'USD', 1.1250), ('2025-06-01', 'EUR', 'USD', 1.1450), ('2025-07-01', 'EUR', 'USD', 1.1750),
    ('2025-08-01', 'EUR', 'USD', 1.1650), ('2025-09-01', 'EUR', 'USD', 1.1720), ('2025-10-01', 'EUR', 'USD', 1.1680),
    ('2025-11-01', 'EUR', 'USD', 1.1580), ('2025-12-01', 'EUR', 'USD', 1.1710), ('2026-01-01', 'EUR', 'USD', 1.1650),
    ('2026-02-01', 'EUR', 'USD', 1.1780), ('2026-03-01', 'EUR', 'USD', 1.1680), ('2026-04-01', 'EUR', 'USD', 1.1580),
    ('2026-05-01', 'EUR', 'USD', 1.1710), ('2026-06-01', 'EUR', 'USD', 1.1620), ('2026-07-01', 'EUR', 'USD', 1.1450),
    ('2024-08-01', 'USD', 'PLN', 3.9520), ('2024-09-01', 'USD', 'PLN', 3.8550), ('2024-10-01', 'USD', 'PLN', 3.8850),
    ('2024-11-01', 'USD', 'PLN', 4.0150), ('2024-12-01', 'USD', 'PLN', 4.1250), ('2025-01-01', 'USD', 'PLN', 4.0520),
    ('2025-02-01', 'USD', 'PLN', 4.0250), ('2025-03-01', 'USD', 'PLN', 3.9850), ('2025-04-01', 'USD', 'PLN', 3.9980),
    ('2025-05-01', 'USD', 'PLN', 3.9250), ('2025-06-01', 'USD', 'PLN', 3.8550), ('2025-07-01', 'USD', 'PLN', 3.7840),
    ('2025-08-01', 'USD', 'PLN', 3.8150), ('2025-09-01', 'USD', 'PLN', 3.8350), ('2025-10-01', 'USD', 'PLN', 3.8210),
    ('2025-11-01', 'USD', 'PLN', 3.8850), ('2025-12-01', 'USD', 'PLN', 3.9250), ('2026-01-01', 'USD', 'PLN', 3.9550),
    ('2026-02-01', 'USD', 'PLN', 3.8850), ('2026-03-01', 'USD', 'PLN', 3.7250), ('2026-04-01', 'USD', 'PLN', 3.6850),
    ('2026-05-01', 'USD', 'PLN', 3.7250), ('2026-06-01', 'USD', 'PLN', 3.7550), ('2026-07-01', 'USD', 'PLN', 3.7450)
ON CONFLICT DO NOTHING;

INSERT INTO investory.assets (name, symbol, ticker, ibkr, yahoo, country, currency, asset_type, active)
VALUES
    ('Broadcom Inc.', '1YD.DE', '1YD', '1YD', '1YD.DE', 'DE', 'EUR', 'EQUITY', false),
    ('Xiaomi Corporation', '3CP.DE', '3CP', '3CP', '3CP.DE', 'DE', 'EUR', 'EQUITY', false),
    ('Apple Inc.', 'AAPL.US', 'AAPL', 'AAPL', 'AAPL.US', 'US', 'USD', 'EQUITY', true),
    ('ABB Ltd', 'ABB.SE', 'ABB', 'ABB', 'ABB.SE', 'SE', 'USD', 'EQUITY', false),
    ('AbbVie Inc.', 'ABBV.US', 'ABBV', 'ABBV', 'ABBV.US', 'US', 'USD', 'EQUITY', false),
    ('Alphabet Inc.', 'ABEA.DE', 'ABEA', 'ABEA', 'ABEA.DE', 'DE', 'EUR', 'EQUITY', false),
    ('Airbnb, Inc.', 'ABNB.US', 'ABNB', 'ABNB', 'ABNB.US', 'US', 'USD', 'EQUITY', false),
    ('Adobe Inc.', 'ADBE.US', 'ADBE', 'ADBE', 'ADBE.US', 'US', 'USD', 'EQUITY', false),
    ('Agree Realty Corporation', 'ADC.US', 'ADC', 'ADC', 'ADC.US', 'US', 'USD', 'REIT', false),
    ('Analog Devices, Inc.', 'ADI.US', 'ADI', 'ADI', 'ADI.US', 'US', 'USD', 'EQUITY', true),
    ('Archer-Daniels-Midland Co', 'ADM.US', 'ADM', 'ADM', 'ADM.US', 'US', 'USD', 'EQUITY', false),
    ('Aedas Homes, S.A.', 'AEDAS.ES', 'AEDAS', 'AEDAS', 'AEDAS.ES', 'ES', 'EUR', 'EQUITY', false),
    ('American Financial Group Inc.', 'AFG.US', 'AFG', 'AFG', 'AFG.US', 'US', 'USD', 'EQUITY', false),
    ('First Majestic Silver Corp', 'AG.US', 'AG', 'AG', 'AG.US', 'US', 'USD', 'EQUITY', false),
    ('iShares Core Global Aggregate Bond UCITS ETF USD (Dist)', 'AGGG.UK', 'AGGG', 'AGGG', 'AGGG.L', 'UK', 'USD', 'ETF', false),
    ('AGNC Investment Corp.', 'AGNC.US', 'AGNC', 'AGNC', 'AGNC.US', 'US', 'USD', 'REIT', true),
    ('Alibaba Group Holding Limited SP ADR', 'AHLA.DE', 'AHLA', 'AHLA', 'AHLA.DE', 'DE', 'EUR', 'EQUITY', false),
    ('WisdomTree Industrial Metals', 'AIGI.UK', 'AIGI', 'AIGI', 'AIGI.L', 'UK', 'USD', 'ETF', false),
    ('Airbus SE', 'AIR.DE', 'AIR', 'AIR', 'AIR.DE', 'DE', 'EUR', 'EQUITY', false),
    ('Allegro.eu S.A.', 'ALE.PL', 'ALE', 'ALE', 'ALE.PL', 'PL', 'PLN', 'EQUITY', false),
    ('Alior Bank S.A.', 'ALR.PL', 'ALR', 'ALR', 'ALR.PL', 'PL', 'PLN', 'EQUITY', false),
    ('Applied Materials, Inc.', 'AMAT.US', 'AMAT', 'AMAT', 'AMAT.US', 'US', 'USD', 'EQUITY', true),
    ('Advanced Micro Devices, Inc.', 'AMD.US', 'AMD', 'AMD', 'AMD.US', 'US', 'USD', 'EQUITY', true),
    ('Amgen Inc.', 'AMGN.US', 'AMGN', 'AMGN', 'AMGN.US', 'US', 'USD', 'EQUITY', false),
    ('American Tower Corporation', 'AMT.US', 'AMT', 'AMT', 'AMT.US', 'US', 'USD', 'REIT', false),
    ('Amazon.com, Inc.', 'AMZN.US', 'AMZN', 'AMZN', 'AMZN.US', 'US', 'USD', 'EQUITY', true),
    ('Arista Networks, Inc.', 'ANET.US', 'ANET', 'ANET', 'ANET.US', 'US', 'USD', 'EQUITY', true),
    ('Applied Digital Corporation', 'APLD.US', 'APLD', 'APLD', 'APLD.US', 'US', 'USD', 'EQUITY', true),
    ('AppLovin Corporation Class A Common Stock', 'APP.US', 'APP', 'APP', 'APP.US', 'US', 'USD', 'EQUITY', false),
    ('Ares Capital Corporation', 'ARCC.US', 'ARCC', 'ARCC', 'ARCC.US', 'US', 'USD', 'FUND', false),
    ('Alexandria Real Estate Equities, Inc.', 'ARE.US', 'ARE', 'ARE', 'ARE.US', 'US', 'USD', 'REIT', false),
    ('Arm Holdings plc American Depositary Receipt', 'ARM.US', 'ARM', 'ARM', 'ARM.US', 'US', 'USD', 'EQUITY', false),
    ('ASML Holding N.V. New York Registry Shares', 'ASML.US', 'ASML', 'ASML', 'ASML.US', 'US', 'USD', 'EQUITY', true),
    ('HANetf Future of Defence UCITS ETF', 'ASWC.DE', 'ASWC', 'ASWC', 'ASWC.DE', 'DE', 'EUR', 'ETF', false),
    ('Broadcom Inc.', 'AVGO.US', 'AVGO', 'AVGO', 'AVGO.US', 'US', 'USD', 'EQUITY', true),
    ('Avery Dennison Corporation', 'AVY.US', 'AVY', 'AVY', 'AVY.US', 'US', 'USD', 'EQUITY', false),
    ('BARRICK MINING CORP Common Stock (ABR0)', 'B.US', 'B', 'GOLD', 'B.US', 'US', 'USD', 'EQUITY', false),
    ('BAE Systems plc', 'BA.UK', 'BA', 'BA', 'BA.L', 'UK', 'USD', 'EQUITY', false),
    ('Alibaba Group Holding Limited SP ADR', 'BABA.US', 'BABA', 'BABA', 'BABA.US', 'US', 'USD', 'EQUITY', true),
    ('Bank of America Corporation', 'BAC.US', 'BAC', 'BAC', 'BAC.US', 'US', 'USD', 'EQUITY', false),
    ('Benefit Systems S.A.', 'BFT.PL', 'BFT', 'BFT', 'BFT.PL', 'PL', 'PLN', 'EQUITY', false),
    ('Burke & Herbert Financial Services Corp.', 'BHRB.US', 'BHRB', 'BHRB', 'BHRB.US', 'US', 'USD', 'EQUITY', false),
    ('Bank Handlowy w Warszawie S.A.', 'BHW.PL', 'BHW', 'BHW', 'BHW.PL', 'PL', 'PLN', 'EQUITY', false),
    ('BITCOIN', 'BITCOIN', 'BITCOIN', 'BITCOIN', 'BITCOIN', 'US', 'USD', 'CRYPTOCURRENCY', false),
    ('BlackRock, Inc.', 'BLK.US', 'BLK', 'BLK', 'BLK.US', 'US', 'USD', 'EQUITY', false),
    ('Bristol-Myers Squibb Company', 'BMY.US', 'BMY', 'BMY', 'BMY.US', 'US', 'USD', 'EQUITY', false),
    ('Berkshire Hathaway Inc. Class B', 'BRKB.US', 'BRKB', 'BRKB', 'BRKB.US', 'US', 'USD', 'EQUITY', false),
    ('Anheuser-Busch InBev S.A. ADR', 'BUD.US', 'BUD', 'BUD', 'BUD.US', 'US', 'USD', 'EQUITY', false),
    ('BYD Company Limited', 'BY6.DE', 'BY6', 'BY6', 'BY6.DE', 'DE', 'EUR', 'EQUITY', false),
    ('Caterpillar Inc.', 'CAT.US', 'CAT', 'CAT', 'CAT.US', 'US', 'USD', 'EQUITY', true),
    ('Chubb Limited', 'CB.US', 'CB', 'CB', 'CB.US', 'US', 'USD', 'EQUITY', false),
    ('The Coca-Cola Company - CDR', 'CCC.PL', 'CCC', 'CCC', 'CCC.PL', 'PL', 'PLN', 'EQUITY', false),
    ('Cameco Corporation', 'CCJ.US', 'CCJ', 'CCJ', 'CCJ.US', 'US', 'USD', 'EQUITY', false),
    ('CD Projekt S.A.', 'CDR.PL', 'CDR', 'CDR', 'CDR.PL', 'PL', 'PLN', 'EQUITY', true),
    ('Church & Dwight Co., Inc.', 'CHD.US', 'CHD', 'CHD', 'CHD.US', 'US', 'USD', 'EQUITY', false),
    ('iShares MSCI Japan UCITS ETF USD (Acc)', 'CJPU.UK', 'CJPU', 'CJPU', 'CJPU.L', 'UK', 'USD', 'ETF', true),
    ('CME Group Inc.', 'CME.US', 'CME', 'CME', 'CME.US', 'US', 'USD', 'EQUITY', false),
    ('iShares NASDAQ 100 UCITS ETF USD (Acc)', 'CNDX.UK', 'CNDX', 'CNDX', 'CNDX.L', 'UK', 'USD', 'ETF', false),
    ('COCOA', 'COCOA', 'COCOA', 'COCOA', 'COCOA', 'US', 'USD', 'COMMODITY', false),
    ('ConocoPhillips', 'COP.US', 'COP', 'COP', 'COP.US', 'US', 'USD', 'EQUITY', false),
    ('Themes Copper Miners ETF', 'COPA.UK', 'COPA', 'COPA', 'COPA.L', 'UK', 'USD', 'ETF', false),
    ('Costco Wholesale Corporation', 'COST.US', 'COST', 'COST', 'COST.US', 'US', 'USD', 'EQUITY', false),
    ('Copart Inc.', 'CPRT.US', 'CPRT', 'CPRT', 'CPRT.US', 'US', 'USD', 'EQUITY', false),
    ('Circle Internet Group, Inc.', 'CRCL.US', 'CRCL', 'CRCL', 'CRCL.US', 'US', 'USD', 'EQUITY', false),
    ('Credo Technology Group Holding Ltd.', 'CRDO.US', 'CRDO', 'CRDO', 'CRDO.US', 'US', 'USD', 'EQUITY', false),
    ('Salesforce Inc', 'CRM.US', 'CRM', 'CRM', 'CRM.US', 'US', 'USD', 'EQUITY', true),
    ('CoreWeave, Inc.', 'CRWV.US', 'CRWV', 'CRWV', 'CRWV.US', 'US', 'USD', 'EQUITY', false),
    ('Cisco Systems, Inc.', 'CSCO.US', 'CSCO', 'CSCO', 'CSCO.US', 'US', 'USD', 'EQUITY', false),
    ('iShares MSCI Korea UCITS ETF USD (Acc)', 'CSKR.UK', 'CSKR', 'CSKR', 'CSKR.L', 'UK', 'USD', 'ETF', true),
    ('iShares Core S&P 500 UCITS ETF USD', 'CSPX.UK', 'CSPX', 'CSPX', 'CSPX.L', 'UK', 'USD', 'ETF', false),
    ('Carvana Co.', 'CVNA.US', 'CVNA', 'CVNA', 'CVNA.US', 'US', 'USD', 'EQUITY', false),
    ('Chevron Corporation', 'CVX.US', 'CVX', 'CVX', 'CVX.US', 'US', 'USD', 'EQUITY', false),
    ('Deutsche Bank AG', 'DBK.DE', 'DBK', 'DBK', 'DBK.DE', 'DE', 'EUR', 'EQUITY', false),
    ('Dakota Gold Corp', 'DC.US', 'DC', 'DC', 'DC.US', 'US', 'USD', 'EQUITY', false),
    ('Datadog, Inc. Class A Common Stock', 'DDOG.US', 'DDOG', 'DDOG', 'DDOG.US', 'US', 'USD', 'EQUITY', false),
    ('VanEck Defense ETF', 'DFEN.DE', 'DFEN', 'DFEN', 'DFEN.DE', 'DE', 'EUR', 'ETF', false),
    ('VanEck Defense ETF', 'DFNS.UK', 'DFNS', 'DFNS', 'DFNS.L', 'UK', 'USD', 'ETF', false),
    ('DLocal Limited', 'DLO.US', 'DLO', 'DLO', 'DLO.US', 'US', 'USD', 'EQUITY', false),
    ('Digital Realty Trust, Inc.', 'DLR.US', 'DLR', 'DLR', 'DLR.US', 'US', 'USD', 'REIT', false),
    ('Dollar Tree, Inc.', 'DLTR.US', 'DLTR', 'DLTR', 'DLTR.US', 'US', 'USD', 'EQUITY', false),
    ('Dino Polska S.A.', 'DNP.PL', 'DNP', 'DNP', 'DNP.PL', 'PL', 'PLN', 'EQUITY', false),
    ('DOGECOIN', 'DOGECOIN', 'DOGECOIN', 'DOGECOIN', 'DOGECOIN', 'US', 'USD', 'CRYPTOCURRENCY', false),
    ('Domino''s Pizza Inc.', 'DPZ.US', 'DPZ', 'DPZ', 'DPZ.US', 'US', 'USD', 'EQUITY', false),
    ('iShares USD Treasury Bond 20+yr UCITS ETF USD (Acc)', 'DTLA.UK', 'DTLA', 'DTLA', 'DTLA.L', 'UK', 'USD', 'ETF', false),
    ('Duolingo, Inc.', 'DUOL.US', 'DUOL', 'DUOL', 'DUOL.US', 'US', 'USD', 'EQUITY', false),
    ('DexCom, Inc.', 'DXCM.US', 'DXCM', 'DXCM', 'DXCM.US', 'US', 'USD', 'EQUITY', false),
    ('iShares Core MSCI Emerging Markets IMI UCITS ETF (Acc)', 'EIMI.UK', 'EIMI', 'EIMI', 'EIMI.L', 'UK', 'USD', 'ETF', false),
    ('iShares Core MSCI Emerging Markets IMI UCITS ETF (Acc)', 'EMIM.UK', 'EMIM', 'EMIM', 'EMIM.L', 'UK', 'USD', 'ETF', false),
    ('Epam Systems Inc.', 'EPAM.US', 'EPAM', 'EPAM', 'EPAM.US', 'US', 'USD', 'EQUITY', false),
    ('Epsilon Energy Ltd.', 'EPSN.US', 'EPSN', 'EPSN', 'EPSN.US', 'US', 'USD', 'EQUITY', false),
    ('Equinix, Inc.', 'EQIX.US', 'EQIX', 'EQIX', 'EQIX.US', 'US', 'USD', 'REIT', false),
    ('Beta ETF Dywidenda Plus Portfelowy Fundusz Inwestycyjny Zamknięty', 'ETFBDIVPL.PL', 'ETFBDIVPL', 'ETFBDIVPL', 'ETFBDIVPL.PL', 'PL', 'PLN', 'ETF', false),
    ('Beta ETF MWIG40TR', 'ETFBM40TR.PL', 'ETFBM40TR', 'ETFBM40TR', 'ETFBM40TR.PL', 'PL', 'PLN', 'ETF', false),
    ('Beta ETF WIG20TR', 'ETFBW20TR.PL', 'ETFBW20TR', 'ETFBW20TR', 'ETFBW20TR.PL', 'PL', 'PLN', 'ETF', true),
    ('ETHEREUM', 'ETHEREUM', 'ETHEREUM', 'ETHEREUM', 'ETHEREUM', 'US', 'USD', 'CRYPTOCURRENCY', false),
    ('Haleon Plc - ADR',     'HLN.US', 'HLN', 'HLN', 'HLN.US','US', 'USD', 'EQUITY', false),
    ('Intuit Inc.','INTU.US', 'INTU', 'INTU', 'INTU.US','US', 'USD', 'EQUITY', false),
    ('iShares Physical Palladium ETC','IPDM.UK', 'IPDM', 'IPDM', 'IPDM.L','UK', 'USD', 'ETF', false),
    ('iShares Physical Platinum ETC',     'IPLT.UK', 'IPLT', 'IPLT', 'IPLT.L','UK', 'USD', 'ETF', false),
    ('iShares Russell 2000 ETF','IWM.US', 'IWM', 'IWM', 'IWM.US','US', 'USD', 'ETF', false),
    ('iShares MSCI India UCITS ETF USD (Acc)','NDIA.UK', 'NDIA', 'NDIA', 'NDIA.L','UK', 'USD', 'ETF', false),
    ('VanEck Semiconductor UCITS ETF','SMH.UK', 'SMH', 'SMH', 'SMH.L','UK', 'USD', 'ETF', false),
    ('Unknown XTB instrument T458022826','T458022826.US', 'T458022826', 'T458022826', 'T458022826.US','US', 'USD', 'EQUITY', false),
    ('W. P. Carey Inc.','WPC.US', 'WPC', 'WPC', 'WPC.US','US', 'USD', 'EQUITY', false)
ON CONFLICT (symbol) DO UPDATE SET
    name = EXCLUDED.name,
    ticker = EXCLUDED.ticker,
    ibkr = EXCLUDED.ibkr,
    yahoo = EXCLUDED.yahoo,
    country = EXCLUDED.country,
    currency = EXCLUDED.currency,
    asset_type = EXCLUDED.asset_type,
    active = EXCLUDED.active;
