-- Generated by scripts/update-test-db-snapshot.sh. Do not edit manually.
-- Source: accounting POC tables and fixtures from the squashed app/src/main/resources/sql/migration chain.
--
-- PostgreSQL database dump
--


-- Dumped from database version 18.6 (Debian 18.6-1.pgdg12+2)
-- Dumped by pg_dump version 18.6 (Debian 18.6-1.pgdg12+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounting_poc_bank_transaction; Type: TABLE; Schema: investory; Owner: -
--

CREATE TABLE investory.accounting_poc_bank_transaction (
    id bigint NOT NULL,
    booking_date date NOT NULL,
    related_period date,
    reference character varying(128),
    counterparty_alias character varying(128),
    currency character(3) NOT NULL,
    amount numeric(19,4) NOT NULL,
    transaction_type character varying(32) NOT NULL,
    scope character varying(32) NOT NULL,
    note character varying(512),
    source_id bigint,
    source_row_identity character varying(256),
    provider character varying(32) NOT NULL,
    external_account_id character varying(256) NOT NULL,
    external_transaction_id character varying(256) CONSTRAINT accounting_poc_bank_transactio_external_transaction_id_not_null NOT NULL,
    source_payload_hash character varying(128),
    profile_id bigint NOT NULL,
    CONSTRAINT chk_accounting_poc_bank_related_period_month_start CHECK (((related_period IS NULL) OR (EXTRACT(day FROM related_period) = (1)::numeric)))
);


--
-- Name: TABLE accounting_poc_bank_transaction; Type: COMMENT; Schema: investory; Owner: -
--

COMMENT ON TABLE investory.accounting_poc_bank_transaction IS 'POC-only anonymized bank fixtures. Private/internal movements are retained but explicitly scoped out.';


--
-- Name: COLUMN accounting_poc_bank_transaction.provider; Type: COMMENT; Schema: investory; Owner: -
--

COMMENT ON COLUMN investory.accounting_poc_bank_transaction.provider IS 'Neutral bank data provider identity; classification remains Accounting-owned.';


--
-- Name: COLUMN accounting_poc_bank_transaction.external_transaction_id; Type: COMMENT; Schema: investory; Owner: -
--

COMMENT ON COLUMN investory.accounting_poc_bank_transaction.external_transaction_id IS 'Provider or deterministic adapter transaction identity used for idempotent ingestion.';


--
-- Name: accounting_poc_bank_transaction_id_seq; Type: SEQUENCE; Schema: investory; Owner: -
--

CREATE SEQUENCE investory.accounting_poc_bank_transaction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: accounting_poc_bank_transaction_id_seq; Type: SEQUENCE OWNED BY; Schema: investory; Owner: -
--

ALTER SEQUENCE investory.accounting_poc_bank_transaction_id_seq OWNED BY investory.accounting_poc_bank_transaction.id;


--
-- Name: accounting_poc_expense_invoice; Type: TABLE; Schema: investory; Owner: -
--

CREATE TABLE investory.accounting_poc_expense_invoice (
    id bigint NOT NULL,
    tax_period date NOT NULL,
    invoice_date date,
    reference character varying(128) NOT NULL,
    supplier_alias character varying(128) NOT NULL,
    category character varying(64) NOT NULL,
    currency character(3) DEFAULT 'PLN'::bpchar NOT NULL,
    net_amount numeric(19,4) NOT NULL,
    vat_amount numeric(19,4) NOT NULL,
    gross_amount numeric(19,4) NOT NULL,
    vat_deduction_ratio numeric(3,2) NOT NULL,
    source_quality character varying(32) NOT NULL,
    note character varying(512),
    source_id bigint,
    counterparty_tax_identifier character varying(32),
    counterparty_country character varying(2),
    ksef_number character varying(256),
    filing_evidence character varying(8),
    profile_id bigint NOT NULL,
    due_date date,
    CONSTRAINT chk_accounting_poc_expense_amounts CHECK (((net_amount + vat_amount) = gross_amount)),
    CONSTRAINT chk_accounting_poc_expense_period_month_start CHECK ((EXTRACT(day FROM tax_period) = (1)::numeric)),
    CONSTRAINT chk_accounting_poc_expense_ratio CHECK ((vat_deduction_ratio = ANY (ARRAY[0.00, 0.50, 1.00])))
);


--
-- Name: TABLE accounting_poc_expense_invoice; Type: COMMENT; Schema: investory; Owner: -
--

COMMENT ON TABLE investory.accounting_poc_expense_invoice IS 'POC-only anonymized expense documents. Deductible VAT is calculated per document as VAT x configured ratio.';


--
-- Name: accounting_poc_expense_invoice_id_seq; Type: SEQUENCE; Schema: investory; Owner: -
--

CREATE SEQUENCE investory.accounting_poc_expense_invoice_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: accounting_poc_expense_invoice_id_seq; Type: SEQUENCE OWNED BY; Schema: investory; Owner: -
--

ALTER SEQUENCE investory.accounting_poc_expense_invoice_id_seq OWNED BY investory.accounting_poc_expense_invoice.id;


--
-- Name: accounting_poc_fact; Type: TABLE; Schema: investory; Owner: -
--

CREATE TABLE investory.accounting_poc_fact (
    id bigint NOT NULL,
    fact_date date,
    fact_type character varying(64) NOT NULL,
    reference character varying(128),
    counterparty_alias character varying(128),
    currency character(3) NOT NULL,
    amount numeric(19,4) NOT NULL,
    tax_rate numeric(7,4),
    note character varying(512),
    profile_id bigint NOT NULL
);


--
-- Name: TABLE accounting_poc_fact; Type: COMMENT; Schema: investory; Owner: -
--

COMMENT ON TABLE investory.accounting_poc_fact IS 'POC-only anonymized accounting facts. Values are historical fixtures, not calculated tax advice.';


--
-- Name: accounting_poc_fact_id_seq; Type: SEQUENCE; Schema: investory; Owner: -
--

CREATE SEQUENCE investory.accounting_poc_fact_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: accounting_poc_fact_id_seq; Type: SEQUENCE OWNED BY; Schema: investory; Owner: -
--

ALTER SEQUENCE investory.accounting_poc_fact_id_seq OWNED BY investory.accounting_poc_fact.id;


--
-- Name: accounting_poc_invoice; Type: TABLE; Schema: investory; Owner: -
--

CREATE TABLE investory.accounting_poc_invoice (
    id bigint NOT NULL,
    tax_period date NOT NULL,
    issue_date date,
    sale_date date,
    fx_rate_date date,
    reference character varying(128) NOT NULL,
    customer_alias character varying(128) NOT NULL,
    invoice_kind character varying(32) NOT NULL,
    currency character(3) NOT NULL,
    net_amount numeric(19,4) NOT NULL,
    vat_amount numeric(19,4) DEFAULT 0 NOT NULL,
    gross_amount numeric(19,4) NOT NULL,
    correction_gross_amount numeric(19,4) DEFAULT 0 NOT NULL,
    correction_net_amount numeric(19,4) DEFAULT 0 NOT NULL,
    correction_vat_amount numeric(19,4) DEFAULT 0 NOT NULL,
    expected_receivable numeric(19,4) NOT NULL,
    booked_net_pln numeric(19,4),
    ryczalt_rate numeric(7,4),
    note character varying(512),
    source_id bigint,
    counterparty_tax_identifier character varying(32),
    counterparty_country character varying(2),
    ksef_number character varying(256),
    filing_evidence character varying(8),
    profile_id bigint NOT NULL,
    due_date date,
    CONSTRAINT chk_accounting_poc_invoice_amounts CHECK (((net_amount + vat_amount) = gross_amount)),
    CONSTRAINT chk_accounting_poc_invoice_period_month_start CHECK ((EXTRACT(day FROM tax_period) = (1)::numeric))
);


--
-- Name: TABLE accounting_poc_invoice; Type: COMMENT; Schema: investory; Owner: -
--

COMMENT ON TABLE investory.accounting_poc_invoice IS 'POC-only anonymized invoice fixtures used for deterministic reconciliation.';


--
-- Name: accounting_poc_invoice_id_seq; Type: SEQUENCE; Schema: investory; Owner: -
--

CREATE SEQUENCE investory.accounting_poc_invoice_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: accounting_poc_invoice_id_seq; Type: SEQUENCE OWNED BY; Schema: investory; Owner: -
--

ALTER SEQUENCE investory.accounting_poc_invoice_id_seq OWNED BY investory.accounting_poc_invoice.id;


--
-- Name: accounting_poc_obligation; Type: TABLE; Schema: investory; Owner: -
--

CREATE TABLE investory.accounting_poc_obligation (
    id bigint NOT NULL,
    tax_period date NOT NULL,
    obligation_type character varying(32) NOT NULL,
    due_date date,
    expected_amount numeric(19,4) NOT NULL,
    paid_amount numeric(19,4) DEFAULT 0 NOT NULL,
    payment_date date,
    status character varying(32) NOT NULL,
    note character varying(512),
    profile_id bigint NOT NULL,
    CONSTRAINT chk_accounting_poc_obligation_period_month_start CHECK ((EXTRACT(day FROM tax_period) = (1)::numeric))
);


--
-- Name: TABLE accounting_poc_obligation; Type: COMMENT; Schema: investory; Owner: -
--

COMMENT ON TABLE investory.accounting_poc_obligation IS 'Historical/golden obligation rows retained for compatibility, not new operational ingestion.';


--
-- Name: accounting_poc_obligation_id_seq; Type: SEQUENCE; Schema: investory; Owner: -
--

CREATE SEQUENCE investory.accounting_poc_obligation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: accounting_poc_obligation_id_seq; Type: SEQUENCE OWNED BY; Schema: investory; Owner: -
--

ALTER SEQUENCE investory.accounting_poc_obligation_id_seq OWNED BY investory.accounting_poc_obligation.id;


--
-- Name: accounting_poc_period_state; Type: TABLE; Schema: investory; Owner: -
--

CREATE TABLE investory.accounting_poc_period_state (
    tax_period date NOT NULL,
    confirmed_at timestamp with time zone,
    confirmed_calculation_hash character varying(64),
    lifecycle_status character varying(32) DEFAULT 'OPEN'::character varying NOT NULL,
    reopened_at timestamp with time zone,
    reopen_reason character varying(1000),
    profile_id bigint NOT NULL,
    CONSTRAINT chk_accounting_period_lifecycle_status CHECK (((lifecycle_status)::text = ANY ((ARRAY['OPEN'::character varying, 'SOURCES_INCOMPLETE'::character varying, 'READY_FOR_REVIEW'::character varying, 'ISSUES'::character varying, 'CONFIRMED'::character varying, 'FILED'::character varying, 'PAID'::character varying, 'SETTLED'::character varying, 'LOCKED'::character varying])::text[]))),
    CONSTRAINT chk_accounting_period_reopen_reason CHECK (((reopened_at IS NULL) OR ((reopen_reason IS NOT NULL) AND (length(btrim((reopen_reason)::text)) > 0)))),
    CONSTRAINT chk_accounting_poc_period_state_month_start CHECK ((EXTRACT(day FROM tax_period) = (1)::numeric))
);


--
-- Name: accounting_poc_profile; Type: TABLE; Schema: investory; Owner: -
--

CREATE TABLE investory.accounting_poc_profile (
    id smallint NOT NULL,
    has_uop boolean NOT NULL,
    nip character varying(10),
    full_name character varying(240),
    tax_office_code character varying(4),
    email character varying(255),
    vat_payment_account character varying(34),
    ryczalt_payment_account character varying(34),
    zus_payment_account character varying(34),
    first_name character varying(120),
    surname character varying(160),
    date_of_birth date,
    profile_id bigint NOT NULL,
    CONSTRAINT chk_accounting_poc_profile_singleton CHECK ((id = 1))
);


--
-- Name: TABLE accounting_poc_profile; Type: COMMENT; Schema: investory; Owner: -
--

COMMENT ON TABLE investory.accounting_poc_profile IS 'Historical compatibility assumptions only; operational taxpayer identity is portfolio-owned.';


--
-- Name: COLUMN accounting_poc_profile.has_uop; Type: COMMENT; Schema: investory; Owner: -
--

COMMENT ON COLUMN investory.accounting_poc_profile.has_uop IS 'True means an active UoP meeting the minimum-remuneration condition for exemption from compulsory JDG social contributions.';


--
-- Name: accounting_poc_tax_input; Type: TABLE; Schema: investory; Owner: -
--

CREATE TABLE investory.accounting_poc_tax_input (
    id bigint NOT NULL,
    tax_period date NOT NULL,
    input_type character varying(64) NOT NULL,
    amount numeric(19,4) NOT NULL,
    note character varying(512),
    profile_id bigint NOT NULL,
    CONSTRAINT chk_accounting_poc_tax_input_period_month_start CHECK ((EXTRACT(day FROM tax_period) = (1)::numeric))
);


--
-- Name: TABLE accounting_poc_tax_input; Type: COMMENT; Schema: investory; Owner: -
--

COMMENT ON TABLE investory.accounting_poc_tax_input IS 'Historical/golden calculation inputs retained for compatibility, not new operational ingestion.';


--
-- Name: accounting_poc_tax_input_id_seq; Type: SEQUENCE; Schema: investory; Owner: -
--

CREATE SEQUENCE investory.accounting_poc_tax_input_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: accounting_poc_tax_input_id_seq; Type: SEQUENCE OWNED BY; Schema: investory; Owner: -
--

ALTER SEQUENCE investory.accounting_poc_tax_input_id_seq OWNED BY investory.accounting_poc_tax_input.id;


--
-- Name: accounting_poc_bank_transaction id; Type: DEFAULT; Schema: investory; Owner: -
--

ALTER TABLE ONLY investory.accounting_poc_bank_transaction ALTER COLUMN id SET DEFAULT nextval('investory.accounting_poc_bank_transaction_id_seq'::regclass);


--
-- Name: accounting_poc_expense_invoice id; Type: DEFAULT; Schema: investory; Owner: -
--

ALTER TABLE ONLY investory.accounting_poc_expense_invoice ALTER COLUMN id SET DEFAULT nextval('investory.accounting_poc_expense_invoice_id_seq'::regclass);


--
-- Name: accounting_poc_fact id; Type: DEFAULT; Schema: investory; Owner: -
--

ALTER TABLE ONLY investory.accounting_poc_fact ALTER COLUMN id SET DEFAULT nextval('investory.accounting_poc_fact_id_seq'::regclass);


--
-- Name: accounting_poc_invoice id; Type: DEFAULT; Schema: investory; Owner: -
--

ALTER TABLE ONLY investory.accounting_poc_invoice ALTER COLUMN id SET DEFAULT nextval('investory.accounting_poc_invoice_id_seq'::regclass);


--
-- Name: accounting_poc_obligation id; Type: DEFAULT; Schema: investory; Owner: -
--

ALTER TABLE ONLY investory.accounting_poc_obligation ALTER COLUMN id SET DEFAULT nextval('investory.accounting_poc_obligation_id_seq'::regclass);


--
-- Name: accounting_poc_tax_input id; Type: DEFAULT; Schema: investory; Owner: -
--

ALTER TABLE ONLY investory.accounting_poc_tax_input ALTER COLUMN id SET DEFAULT nextval('investory.accounting_poc_tax_input_id_seq'::regclass);


--
-- Data for Name: accounting_poc_bank_transaction; Type: TABLE DATA; Schema: investory; Owner: -
--

COPY investory.accounting_poc_bank_transaction (id, booking_date, related_period, reference, counterparty_alias, currency, amount, transaction_type, scope, note, source_id, source_row_identity, provider, external_account_id, external_transaction_id, source_payload_hash, profile_id) FROM stdin;
\.


--
-- Data for Name: accounting_poc_expense_invoice; Type: TABLE DATA; Schema: investory; Owner: -
--

COPY investory.accounting_poc_expense_invoice (id, tax_period, invoice_date, reference, supplier_alias, category, currency, net_amount, vat_amount, gross_amount, vat_deduction_ratio, source_quality, note, source_id, counterparty_tax_identifier, counterparty_country, ksef_number, filing_evidence, profile_id, due_date) FROM stdin;
\.


--
-- Data for Name: accounting_poc_fact; Type: TABLE DATA; Schema: investory; Owner: -
--

COPY investory.accounting_poc_fact (id, fact_date, fact_type, reference, counterparty_alias, currency, amount, tax_rate, note, profile_id) FROM stdin;
\.


--
-- Data for Name: accounting_poc_invoice; Type: TABLE DATA; Schema: investory; Owner: -
--

COPY investory.accounting_poc_invoice (id, tax_period, issue_date, sale_date, fx_rate_date, reference, customer_alias, invoice_kind, currency, net_amount, vat_amount, gross_amount, correction_gross_amount, correction_net_amount, correction_vat_amount, expected_receivable, booked_net_pln, ryczalt_rate, note, source_id, counterparty_tax_identifier, counterparty_country, ksef_number, filing_evidence, profile_id, due_date) FROM stdin;
\.


--
-- Data for Name: accounting_poc_obligation; Type: TABLE DATA; Schema: investory; Owner: -
--

COPY investory.accounting_poc_obligation (id, tax_period, obligation_type, due_date, expected_amount, paid_amount, payment_date, status, note, profile_id) FROM stdin;
\.


--
-- Data for Name: accounting_poc_period_state; Type: TABLE DATA; Schema: investory; Owner: -
--

COPY investory.accounting_poc_period_state (tax_period, confirmed_at, confirmed_calculation_hash, lifecycle_status, reopened_at, reopen_reason, profile_id) FROM stdin;
\.


--
-- Data for Name: accounting_poc_profile; Type: TABLE DATA; Schema: investory; Owner: -
--

COPY investory.accounting_poc_profile (id, has_uop, nip, full_name, tax_office_code, email, vat_payment_account, ryczalt_payment_account, zus_payment_account, first_name, surname, date_of_birth, profile_id) FROM stdin;
1	t	1010000000	Investory Accounting POC	1215	accounting@example.invalid	\N	\N	\N	\N	\N	\N	1
\.


--
-- Data for Name: accounting_poc_tax_input; Type: TABLE DATA; Schema: investory; Owner: -
--

COPY investory.accounting_poc_tax_input (id, tax_period, input_type, amount, note, profile_id) FROM stdin;
\.


--
-- Name: accounting_poc_bank_transaction_id_seq; Type: SEQUENCE SET; Schema: investory; Owner: -
--

SELECT pg_catalog.setval('investory.accounting_poc_bank_transaction_id_seq', 20, true);


--
-- Name: accounting_poc_expense_invoice_id_seq; Type: SEQUENCE SET; Schema: investory; Owner: -
--

SELECT pg_catalog.setval('investory.accounting_poc_expense_invoice_id_seq', 23, true);


--
-- Name: accounting_poc_fact_id_seq; Type: SEQUENCE SET; Schema: investory; Owner: -
--

SELECT pg_catalog.setval('investory.accounting_poc_fact_id_seq', 10, true);


--
-- Name: accounting_poc_invoice_id_seq; Type: SEQUENCE SET; Schema: investory; Owner: -
--

SELECT pg_catalog.setval('investory.accounting_poc_invoice_id_seq', 15, true);


--
-- Name: accounting_poc_obligation_id_seq; Type: SEQUENCE SET; Schema: investory; Owner: -
--

SELECT pg_catalog.setval('investory.accounting_poc_obligation_id_seq', 22, true);


--
-- Name: accounting_poc_tax_input_id_seq; Type: SEQUENCE SET; Schema: investory; Owner: -
--

SELECT pg_catalog.setval('investory.accounting_poc_tax_input_id_seq', 31, true);


--
-- Name: accounting_poc_bank_transaction accounting_poc_bank_transaction_pkey; Type: CONSTRAINT; Schema: investory; Owner: -
--

ALTER TABLE ONLY investory.accounting_poc_bank_transaction
    ADD CONSTRAINT accounting_poc_bank_transaction_pkey PRIMARY KEY (id);


--
-- Name: accounting_poc_expense_invoice accounting_poc_expense_invoice_pkey; Type: CONSTRAINT; Schema: investory; Owner: -
--

ALTER TABLE ONLY investory.accounting_poc_expense_invoice
    ADD CONSTRAINT accounting_poc_expense_invoice_pkey PRIMARY KEY (id);


--
-- Name: accounting_poc_fact accounting_poc_fact_pkey; Type: CONSTRAINT; Schema: investory; Owner: -
--

ALTER TABLE ONLY investory.accounting_poc_fact
    ADD CONSTRAINT accounting_poc_fact_pkey PRIMARY KEY (id);


--
-- Name: accounting_poc_invoice accounting_poc_invoice_pkey; Type: CONSTRAINT; Schema: investory; Owner: -
--

ALTER TABLE ONLY investory.accounting_poc_invoice
    ADD CONSTRAINT accounting_poc_invoice_pkey PRIMARY KEY (id);


--
-- Name: accounting_poc_obligation accounting_poc_obligation_pkey; Type: CONSTRAINT; Schema: investory; Owner: -
--

ALTER TABLE ONLY investory.accounting_poc_obligation
    ADD CONSTRAINT accounting_poc_obligation_pkey PRIMARY KEY (id);


--
-- Name: accounting_poc_profile accounting_poc_profile_pkey; Type: CONSTRAINT; Schema: investory; Owner: -
--

ALTER TABLE ONLY investory.accounting_poc_profile
    ADD CONSTRAINT accounting_poc_profile_pkey PRIMARY KEY (id);


--
-- Name: accounting_poc_tax_input accounting_poc_tax_input_pkey; Type: CONSTRAINT; Schema: investory; Owner: -
--

ALTER TABLE ONLY investory.accounting_poc_tax_input
    ADD CONSTRAINT accounting_poc_tax_input_pkey PRIMARY KEY (id);


--
-- Name: accounting_poc_period_state pk_accounting_poc_period_state; Type: CONSTRAINT; Schema: investory; Owner: -
--

ALTER TABLE ONLY investory.accounting_poc_period_state
    ADD CONSTRAINT pk_accounting_poc_period_state PRIMARY KEY (profile_id, tax_period);


--
-- Name: idx_accounting_poc_bank_related_period; Type: INDEX; Schema: investory; Owner: -
--

CREATE INDEX idx_accounting_poc_bank_related_period ON investory.accounting_poc_bank_transaction USING btree (related_period, booking_date, id);


--
-- Name: idx_accounting_poc_bank_source_id; Type: INDEX; Schema: investory; Owner: -
--

CREATE INDEX idx_accounting_poc_bank_source_id ON investory.accounting_poc_bank_transaction USING btree (source_id);


--
-- Name: idx_accounting_poc_expense_period; Type: INDEX; Schema: investory; Owner: -
--

CREATE INDEX idx_accounting_poc_expense_period ON investory.accounting_poc_expense_invoice USING btree (tax_period, invoice_date, id);


--
-- Name: idx_accounting_poc_expense_source_id; Type: INDEX; Schema: investory; Owner: -
--

CREATE INDEX idx_accounting_poc_expense_source_id ON investory.accounting_poc_expense_invoice USING btree (source_id);


--
-- Name: idx_accounting_poc_fact_date; Type: INDEX; Schema: investory; Owner: -
--

CREATE INDEX idx_accounting_poc_fact_date ON investory.accounting_poc_fact USING btree (fact_date DESC, id DESC);


--
-- Name: idx_accounting_poc_invoice_period; Type: INDEX; Schema: investory; Owner: -
--

CREATE INDEX idx_accounting_poc_invoice_period ON investory.accounting_poc_invoice USING btree (tax_period, id);


--
-- Name: idx_accounting_poc_invoice_source_id; Type: INDEX; Schema: investory; Owner: -
--

CREATE INDEX idx_accounting_poc_invoice_source_id ON investory.accounting_poc_invoice USING btree (source_id);


--
-- Name: idx_accounting_poc_obligation_period; Type: INDEX; Schema: investory; Owner: -
--

CREATE INDEX idx_accounting_poc_obligation_period ON investory.accounting_poc_obligation USING btree (tax_period, obligation_type);


--
-- Name: ix_accounting_poc_bank_profile_match; Type: INDEX; Schema: investory; Owner: -
--

CREATE INDEX ix_accounting_poc_bank_profile_match ON investory.accounting_poc_bank_transaction USING btree (profile_id, booking_date, amount, currency);


--
-- Name: ix_accounting_poc_expense_profile_reference; Type: INDEX; Schema: investory; Owner: -
--

CREATE INDEX ix_accounting_poc_expense_profile_reference ON investory.accounting_poc_expense_invoice USING btree (profile_id, reference);


--
-- Name: ix_accounting_poc_fact_profile_date; Type: INDEX; Schema: investory; Owner: -
--

CREATE INDEX ix_accounting_poc_fact_profile_date ON investory.accounting_poc_fact USING btree (profile_id, fact_date, id);


--
-- Name: ix_accounting_poc_invoice_profile_reference; Type: INDEX; Schema: investory; Owner: -
--

CREATE INDEX ix_accounting_poc_invoice_profile_reference ON investory.accounting_poc_invoice USING btree (profile_id, reference);


--
-- Name: uq_accounting_poc_bank_profile_external_transaction; Type: INDEX; Schema: investory; Owner: -
--

CREATE UNIQUE INDEX uq_accounting_poc_bank_profile_external_transaction ON investory.accounting_poc_bank_transaction USING btree (profile_id, provider, external_account_id, external_transaction_id);


--
-- Name: uq_accounting_poc_bank_profile_source_row; Type: INDEX; Schema: investory; Owner: -
--

CREATE UNIQUE INDEX uq_accounting_poc_bank_profile_source_row ON investory.accounting_poc_bank_transaction USING btree (profile_id, source_row_identity) WHERE (source_row_identity IS NOT NULL);


--
-- Name: uq_accounting_poc_expense_profile_id; Type: INDEX; Schema: investory; Owner: -
--

CREATE UNIQUE INDEX uq_accounting_poc_expense_profile_id ON investory.accounting_poc_expense_invoice USING btree (profile_id, id);


--
-- Name: uq_accounting_poc_expense_profile_ksef; Type: INDEX; Schema: investory; Owner: -
--

CREATE UNIQUE INDEX uq_accounting_poc_expense_profile_ksef ON investory.accounting_poc_expense_invoice USING btree (profile_id, ksef_number) WHERE (ksef_number IS NOT NULL);


--
-- Name: uq_accounting_poc_expense_profile_reference; Type: INDEX; Schema: investory; Owner: -
--

CREATE UNIQUE INDEX uq_accounting_poc_expense_profile_reference ON investory.accounting_poc_expense_invoice USING btree (profile_id, reference);


--
-- Name: uq_accounting_poc_invoice_profile_id; Type: INDEX; Schema: investory; Owner: -
--

CREATE UNIQUE INDEX uq_accounting_poc_invoice_profile_id ON investory.accounting_poc_invoice USING btree (profile_id, id);


--
-- Name: uq_accounting_poc_invoice_profile_ksef; Type: INDEX; Schema: investory; Owner: -
--

CREATE UNIQUE INDEX uq_accounting_poc_invoice_profile_ksef ON investory.accounting_poc_invoice USING btree (profile_id, ksef_number) WHERE (ksef_number IS NOT NULL);


--
-- Name: uq_accounting_poc_invoice_profile_reference; Type: INDEX; Schema: investory; Owner: -
--

CREATE UNIQUE INDEX uq_accounting_poc_invoice_profile_reference ON investory.accounting_poc_invoice USING btree (profile_id, reference);


--
-- Name: uq_accounting_poc_obligation_profile_period_type; Type: INDEX; Schema: investory; Owner: -
--

CREATE UNIQUE INDEX uq_accounting_poc_obligation_profile_period_type ON investory.accounting_poc_obligation USING btree (profile_id, tax_period, obligation_type);


--
-- Name: uq_accounting_poc_tax_input_profile_period_type; Type: INDEX; Schema: investory; Owner: -
--

CREATE UNIQUE INDEX uq_accounting_poc_tax_input_profile_period_type ON investory.accounting_poc_tax_input USING btree (profile_id, tax_period, input_type);


--
-- Name: accounting_poc_bank_transaction accounting_poc_bank_transaction_profile_id_fkey; Type: FK CONSTRAINT; Schema: investory; Owner: -
--

ALTER TABLE ONLY investory.accounting_poc_bank_transaction
    ADD CONSTRAINT accounting_poc_bank_transaction_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES investory.portfolios(id);


--
-- Name: accounting_poc_expense_invoice accounting_poc_expense_invoice_profile_id_fkey; Type: FK CONSTRAINT; Schema: investory; Owner: -
--

ALTER TABLE ONLY investory.accounting_poc_expense_invoice
    ADD CONSTRAINT accounting_poc_expense_invoice_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES investory.portfolios(id);


--
-- Name: accounting_poc_fact accounting_poc_fact_profile_id_fkey; Type: FK CONSTRAINT; Schema: investory; Owner: -
--

ALTER TABLE ONLY investory.accounting_poc_fact
    ADD CONSTRAINT accounting_poc_fact_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES investory.portfolios(id);


--
-- Name: accounting_poc_invoice accounting_poc_invoice_profile_id_fkey; Type: FK CONSTRAINT; Schema: investory; Owner: -
--

ALTER TABLE ONLY investory.accounting_poc_invoice
    ADD CONSTRAINT accounting_poc_invoice_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES investory.portfolios(id);


--
-- Name: accounting_poc_obligation accounting_poc_obligation_profile_id_fkey; Type: FK CONSTRAINT; Schema: investory; Owner: -
--

ALTER TABLE ONLY investory.accounting_poc_obligation
    ADD CONSTRAINT accounting_poc_obligation_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES investory.portfolios(id);


--
-- Name: accounting_poc_period_state accounting_poc_period_state_profile_id_fkey; Type: FK CONSTRAINT; Schema: investory; Owner: -
--

ALTER TABLE ONLY investory.accounting_poc_period_state
    ADD CONSTRAINT accounting_poc_period_state_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES investory.portfolios(id);


--
-- Name: accounting_poc_profile accounting_poc_profile_profile_id_fkey; Type: FK CONSTRAINT; Schema: investory; Owner: -
--

ALTER TABLE ONLY investory.accounting_poc_profile
    ADD CONSTRAINT accounting_poc_profile_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES investory.portfolios(id);


--
-- Name: accounting_poc_tax_input accounting_poc_tax_input_profile_id_fkey; Type: FK CONSTRAINT; Schema: investory; Owner: -
--

ALTER TABLE ONLY investory.accounting_poc_tax_input
    ADD CONSTRAINT accounting_poc_tax_input_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES investory.portfolios(id);


--
-- Name: accounting_poc_bank_transaction fk_accounting_poc_bank_profile_source; Type: FK CONSTRAINT; Schema: investory; Owner: -
--

ALTER TABLE ONLY investory.accounting_poc_bank_transaction
    ADD CONSTRAINT fk_accounting_poc_bank_profile_source FOREIGN KEY (profile_id, source_id) REFERENCES investory.accounting_source_evidence(profile_id, id);


--
-- Name: accounting_poc_expense_invoice fk_accounting_poc_expense_profile_source; Type: FK CONSTRAINT; Schema: investory; Owner: -
--

ALTER TABLE ONLY investory.accounting_poc_expense_invoice
    ADD CONSTRAINT fk_accounting_poc_expense_profile_source FOREIGN KEY (profile_id, source_id) REFERENCES investory.accounting_source_evidence(profile_id, id);


--
-- Name: accounting_poc_invoice fk_accounting_poc_invoice_profile_source; Type: FK CONSTRAINT; Schema: investory; Owner: -
--

ALTER TABLE ONLY investory.accounting_poc_invoice
    ADD CONSTRAINT fk_accounting_poc_invoice_profile_source FOREIGN KEY (profile_id, source_id) REFERENCES investory.accounting_source_evidence(profile_id, id);


--
-- PostgreSQL database dump complete
--


